// GENERATED FILE -- DO NOT EDIT BY HAND.
//
// Regenerate with:
//   dart run tool/generate_coverage_aggregator.dart
//
// `flutter test --coverage` instruments only the libraries a run loads. A file
// no test imports is absent from lcov.info entirely -- not reported as 0% -- so
// it never reaches the denominator and every layer percentage reads higher than
// the truth. Importing every eligible library here forces all of them into the
// report.
//
// The test below fails when this list drifts from the filesystem, so a new file
// under lib/ cannot quietly escape measurement.
//
// ignore_for_file: unused_import

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:grex/core/config/app_config.dart';
import 'package:grex/core/config/env_config.dart';
import 'package:grex/core/config/supabase_config.dart';
import 'package:grex/core/constants/api_endpoints.dart';
import 'package:grex/core/constants/app_constants.dart';
import 'package:grex/core/di/injection.dart';
import 'package:grex/core/di/main_app_injection.dart';
import 'package:grex/core/di/providers.dart';
import 'package:grex/core/errors/dio_exception_mapper.dart';
import 'package:grex/core/errors/exception_to_failure_mapper.dart';
import 'package:grex/core/errors/exceptions.dart';
import 'package:grex/core/errors/failures.dart';
import 'package:grex/core/feature_flags/feature_flags_manager.dart';
import 'package:grex/core/localization/localization_providers.dart';
import 'package:grex/core/localization/localization_service.dart';
import 'package:grex/core/localization/localized_formatters.dart';
import 'package:grex/core/logging/log_level.dart';
import 'package:grex/core/logging/log_output.dart';
import 'package:grex/core/logging/logging_examples.dart';
import 'package:grex/core/logging/logging_providers.dart';
import 'package:grex/core/logging/logging_service.dart';
import 'package:grex/core/network/api_client.dart';
import 'package:grex/core/network/interceptors/api_logging_interceptor.dart';
import 'package:grex/core/network/interceptors/auth_interceptor.dart';
import 'package:grex/core/network/interceptors/cache_interceptor.dart';
import 'package:grex/core/network/interceptors/error_interceptor.dart';
import 'package:grex/core/network/interceptors/logging_interceptor.dart';
import 'package:grex/core/network/interceptors/performance_interceptor.dart';
import 'package:grex/core/performance/performance.dart';
import 'package:grex/core/performance/performance_attributes.dart';
import 'package:grex/core/performance/performance_examples.dart';
import 'package:grex/core/performance/performance_providers.dart';
import 'package:grex/core/performance/performance_repository_mixin.dart';
import 'package:grex/core/performance/performance_screen_mixin.dart';
import 'package:grex/core/performance/performance_service.dart';
import 'package:grex/core/performance/performance_usecase_mixin.dart';
import 'package:grex/core/performance/performance_utils.dart';
import 'package:grex/core/routing/app_router.dart';
import 'package:grex/core/routing/app_routes.dart';
import 'package:grex/core/routing/auth_navigation_extensions.dart';
import 'package:grex/core/routing/navigation_extensions.dart';
import 'package:grex/core/routing/navigation_logging.dart';
import 'package:grex/core/routing/router_delegate.dart';
import 'package:grex/core/routing/routing_providers.dart';
import 'package:grex/core/routing/widgets/breadcrumb_navigation.dart';
import 'package:grex/core/services/error_logging_service.dart';
import 'package:grex/core/services/export_service.dart';
import 'package:grex/core/services/offline_queue_storage.dart';
import 'package:grex/core/services/real_time_manager.dart';
import 'package:grex/core/services/real_time_service.dart';
import 'package:grex/core/services/retry_service.dart';
import 'package:grex/core/storage/migration/migration_executor.dart';
import 'package:grex/core/storage/migration/migration_registry.dart';
import 'package:grex/core/storage/migration/migrations/migration_v1_to_v2.dart';
import 'package:grex/core/storage/migration/storage_migration.dart';
import 'package:grex/core/storage/secure_storage_service.dart';
import 'package:grex/core/storage/storage_logging_mixin.dart';
import 'package:grex/core/storage/storage_migration_service.dart';
import 'package:grex/core/storage/storage_service.dart';
import 'package:grex/core/storage/storage_version.dart';
import 'package:grex/core/utils/date_formatter.dart';
import 'package:grex/core/utils/debouncer.dart';
import 'package:grex/core/utils/image_cache_helper.dart';
import 'package:grex/core/utils/json_helper.dart';
import 'package:grex/core/utils/lazy_loader.dart';
import 'package:grex/core/utils/memory_helper.dart';
import 'package:grex/core/utils/pagination_helper.dart';
import 'package:grex/core/utils/performance_monitor.dart';
import 'package:grex/core/utils/provider_disposal.dart';
import 'package:grex/core/utils/result.dart';
import 'package:grex/core/utils/validators.dart';
import 'package:grex/core/widgets/error_display_widget.dart';
import 'package:grex/core/widgets/global_error_handler.dart';
import 'package:grex/features/auth/data/handlers/auth_deep_link_handler.dart';
import 'package:grex/features/auth/data/models/user_model.dart';
import 'package:grex/features/auth/data/repositories/repositories.dart';
import 'package:grex/features/auth/data/repositories/supabase_auth_repository.dart';
import 'package:grex/features/auth/data/repositories/supabase_social_auth_repository.dart';
import 'package:grex/features/auth/data/repositories/supabase_user_repository.dart';
import 'package:grex/features/auth/data/services/native_apple_sign_in_service_impl.dart';
import 'package:grex/features/auth/data/services/native_google_sign_in_service_impl.dart';
import 'package:grex/features/auth/data/services/nonce_generator_impl.dart';
import 'package:grex/features/auth/data/services/optimized_session_service.dart';
import 'package:grex/features/auth/data/services/secure_session_service.dart';
import 'package:grex/features/auth/data/services/supabase_email_verification_service.dart';
import 'package:grex/features/auth/data/utils/social_auth_error_mapper.dart';
import 'package:grex/features/auth/domain/auth_domain.dart';
import 'package:grex/features/auth/domain/entities/entities.dart';
import 'package:grex/features/auth/domain/entities/failures.dart';
import 'package:grex/features/auth/domain/entities/profile_setup_data.dart';
import 'package:grex/features/auth/domain/entities/social_auth_provider.dart';
import 'package:grex/features/auth/domain/entities/user.dart';
import 'package:grex/features/auth/domain/entities/user_profile.dart';
import 'package:grex/features/auth/domain/failures/user_failure.dart';
import 'package:grex/features/auth/domain/repositories/auth_repository.dart';
import 'package:grex/features/auth/domain/repositories/repositories.dart';
import 'package:grex/features/auth/domain/repositories/social_auth_repository.dart';
import 'package:grex/features/auth/domain/repositories/user_repository.dart';
import 'package:grex/features/auth/domain/services/auth_deep_link_handler.dart';
import 'package:grex/features/auth/domain/services/email_verification_service.dart';
import 'package:grex/features/auth/domain/services/native_apple_sign_in_service.dart';
import 'package:grex/features/auth/domain/services/native_google_sign_in_service.dart';
import 'package:grex/features/auth/domain/services/nonce_generator.dart';
import 'package:grex/features/auth/domain/services/oauth_scope_validator.dart';
import 'package:grex/features/auth/domain/services/session_manager.dart';
import 'package:grex/features/auth/domain/services/session_service.dart';
import 'package:grex/features/auth/domain/services/simple_session_service.dart';
import 'package:grex/features/auth/domain/services/social_login_analytics.dart';
import 'package:grex/features/auth/domain/usecases/get_current_user_usecase.dart';
import 'package:grex/features/auth/domain/usecases/is_authenticated_usecase.dart';
import 'package:grex/features/auth/domain/usecases/login_usecase.dart';
import 'package:grex/features/auth/domain/usecases/logout_usecase.dart';
import 'package:grex/features/auth/domain/usecases/refresh_token_usecase.dart';
import 'package:grex/features/auth/domain/usecases/register_usecase.dart';
import 'package:grex/features/auth/domain/validators/input_validators.dart';
import 'package:grex/features/auth/domain/validators/validators.dart';
import 'package:grex/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:grex/features/auth/presentation/bloc/auth_event.dart';
import 'package:grex/features/auth/presentation/bloc/auth_state.dart';
import 'package:grex/features/auth/presentation/bloc/bloc.dart';
import 'package:grex/features/auth/presentation/bloc/profile_bloc.dart';
import 'package:grex/features/auth/presentation/bloc/profile_event.dart';
import 'package:grex/features/auth/presentation/bloc/profile_state.dart';
import 'package:grex/features/auth/presentation/pages/edit_profile_page.dart';
import 'package:grex/features/auth/presentation/pages/email_verification_page.dart';
import 'package:grex/features/auth/presentation/pages/forgot_password_page.dart';
import 'package:grex/features/auth/presentation/pages/login_page.dart';
import 'package:grex/features/auth/presentation/pages/pages.dart';
import 'package:grex/features/auth/presentation/pages/profile_page.dart';
import 'package:grex/features/auth/presentation/pages/profile_setup_page.dart';
import 'package:grex/features/auth/presentation/pages/register_page.dart';
import 'package:grex/features/auth/presentation/pages/reset_password_page.dart';
import 'package:grex/features/auth/presentation/providers/auth_provider.dart';
import 'package:grex/features/auth/presentation/screens/auth_screen_wrappers.dart';
import 'package:grex/features/auth/presentation/utils/social_auth_error_handler.dart';
import 'package:grex/features/auth/presentation/widgets/account_linking_dialog.dart';
import 'package:grex/features/auth/presentation/widgets/app_link_listener.dart';
import 'package:grex/features/auth/presentation/widgets/app_logo.dart';
import 'package:grex/features/auth/presentation/widgets/auth_button.dart';
import 'package:grex/features/auth/presentation/widgets/auth_text_field.dart';
import 'package:grex/features/auth/presentation/widgets/error_banner.dart';
import 'package:grex/features/auth/presentation/widgets/loading_overlay.dart';
import 'package:grex/features/auth/presentation/widgets/or_divider.dart';
import 'package:grex/features/auth/presentation/widgets/password_requirement_indicator.dart';
import 'package:grex/features/auth/presentation/widgets/primary_button.dart';
import 'package:grex/features/auth/presentation/widgets/social_auth_error_widget.dart';
import 'package:grex/features/auth/presentation/widgets/social_login_button.dart';
import 'package:grex/features/auth/presentation/widgets/success_screen.dart';
import 'package:grex/features/auth/presentation/widgets/widgets.dart';
import 'package:grex/features/balances/data/models/balance_model.dart';
import 'package:grex/features/balances/data/models/models.dart';
import 'package:grex/features/balances/data/models/settlement_model.dart';
import 'package:grex/features/balances/data/repositories/repositories.dart';
import 'package:grex/features/balances/data/repositories/supabase_balance_repository.dart';
import 'package:grex/features/balances/domain/entities/balance.dart';
import 'package:grex/features/balances/domain/entities/entities.dart';
import 'package:grex/features/balances/domain/entities/settlement.dart';
import 'package:grex/features/balances/domain/failures/balance_failure.dart';
import 'package:grex/features/balances/domain/failures/failures.dart';
import 'package:grex/features/balances/domain/repositories/balance_repository.dart';
import 'package:grex/features/balances/presentation/bloc/balance_bloc.dart';
import 'package:grex/features/balances/presentation/bloc/balance_event.dart';
import 'package:grex/features/balances/presentation/bloc/balance_state.dart';
import 'package:grex/features/balances/presentation/pages/balance_page.dart';
import 'package:grex/features/balances/presentation/pages/settlement_plan_page.dart';
import 'package:grex/features/balances/presentation/widgets/balance_list_error_widget.dart';
import 'package:grex/features/balances/presentation/widgets/balance_list_item.dart';
import 'package:grex/features/balances/presentation/widgets/balance_list_skeleton.dart';
import 'package:grex/features/balances/presentation/widgets/balance_summary_card.dart';
import 'package:grex/features/balances/presentation/widgets/empty_balances_widget.dart';
import 'package:grex/features/balances/presentation/widgets/empty_settlement_widget.dart';
import 'package:grex/features/balances/presentation/widgets/settlement_list_item.dart';
import 'package:grex/features/balances/presentation/widgets/settlement_summary_card.dart';
import 'package:grex/features/expenses/data/models/expense_model.dart';
import 'package:grex/features/expenses/data/models/expense_participant_model.dart';
import 'package:grex/features/expenses/data/models/models.dart';
import 'package:grex/features/expenses/data/repositories/repositories.dart';
import 'package:grex/features/expenses/data/repositories/supabase_expense_repository.dart';
import 'package:grex/features/expenses/domain/entities/entities.dart';
import 'package:grex/features/expenses/domain/entities/expense.dart';
import 'package:grex/features/expenses/domain/entities/expense_participant.dart';
import 'package:grex/features/expenses/domain/entities/split_method.dart';
import 'package:grex/features/expenses/domain/failures/expense_failure.dart';
import 'package:grex/features/expenses/domain/failures/failures.dart';
import 'package:grex/features/expenses/domain/repositories/expense_repository.dart';
import 'package:grex/features/expenses/domain/utils/expense_calculator.dart';
import 'package:grex/features/expenses/domain/utils/expense_search_filter.dart';
import 'package:grex/features/expenses/presentation/bloc/expense_bloc.dart';
import 'package:grex/features/expenses/presentation/bloc/expense_event.dart';
import 'package:grex/features/expenses/presentation/bloc/expense_state.dart';
import 'package:grex/features/expenses/presentation/pages/create_expense_page.dart';
import 'package:grex/features/expenses/presentation/pages/edit_expense_page.dart';
import 'package:grex/features/expenses/presentation/pages/expense_details_page.dart';
import 'package:grex/features/expenses/presentation/pages/expense_list_page.dart';
import 'package:grex/features/expenses/presentation/widgets/empty_expenses_widget.dart';
import 'package:grex/features/expenses/presentation/widgets/expense_actions_widget.dart';
import 'package:grex/features/expenses/presentation/widgets/expense_filter_sheet.dart';
import 'package:grex/features/expenses/presentation/widgets/expense_list_error_widget.dart';
import 'package:grex/features/expenses/presentation/widgets/expense_list_item.dart';
import 'package:grex/features/expenses/presentation/widgets/expense_list_skeleton.dart';
import 'package:grex/features/expenses/presentation/widgets/expense_participant_list.dart';
import 'package:grex/features/expenses/presentation/widgets/expense_search_bar.dart';
import 'package:grex/features/expenses/presentation/widgets/participant_selection_widget.dart';
import 'package:grex/features/expenses/presentation/widgets/split_configuration_widget.dart';
import 'package:grex/features/expenses/presentation/widgets/split_method_selector.dart';
import 'package:grex/features/export/presentation/pages/export_page.dart';
import 'package:grex/features/export/presentation/widgets/export_format_selector.dart';
import 'package:grex/features/export/presentation/widgets/export_progress_dialog.dart';
import 'package:grex/features/feature_flags/data/datasources/feature_flags_local_datasource.dart';
import 'package:grex/features/feature_flags/data/datasources/feature_flags_remote_datasource.dart';
import 'package:grex/features/feature_flags/data/repositories/feature_flags_repository_impl.dart';
import 'package:grex/features/feature_flags/data/services/local_feature_flags_service.dart';
import 'package:grex/features/feature_flags/domain/entities/feature_flag.dart';
import 'package:grex/features/feature_flags/domain/repositories/feature_flags_repository.dart';
import 'package:grex/features/feature_flags/presentation/examples/feature_flags_example_screen.dart';
import 'package:grex/features/feature_flags/presentation/providers/feature_flags_providers.dart';
import 'package:grex/features/feature_flags/presentation/screens/feature_flags_debug_screen.dart';
import 'package:grex/features/feature_flags/presentation/widgets/feature_flag_builder.dart';
import 'package:grex/features/groups/data/models/group_member_model.dart';
import 'package:grex/features/groups/data/models/group_model.dart';
import 'package:grex/features/groups/data/models/models.dart';
import 'package:grex/features/groups/data/repositories/repositories.dart';
import 'package:grex/features/groups/data/repositories/supabase_group_repository.dart';
import 'package:grex/features/groups/domain/entities/entities.dart';
import 'package:grex/features/groups/domain/entities/group.dart';
import 'package:grex/features/groups/domain/entities/group_member.dart';
import 'package:grex/features/groups/domain/entities/member_role.dart';
import 'package:grex/features/groups/domain/failures/failures.dart';
import 'package:grex/features/groups/domain/failures/group_failure.dart';
import 'package:grex/features/groups/domain/repositories/group_repository.dart';
import 'package:grex/features/groups/presentation/bloc/group_bloc.dart';
import 'package:grex/features/groups/presentation/bloc/group_event.dart';
import 'package:grex/features/groups/presentation/bloc/group_state.dart';
import 'package:grex/features/groups/presentation/pages/create_group_page.dart';
import 'package:grex/features/groups/presentation/pages/group_details_page.dart';
import 'package:grex/features/groups/presentation/pages/group_list_page.dart';
import 'package:grex/features/groups/presentation/pages/group_settings_page.dart';
import 'package:grex/features/groups/presentation/widgets/empty_groups_widget.dart';
import 'package:grex/features/groups/presentation/widgets/group_list_error_widget.dart';
import 'package:grex/features/groups/presentation/widgets/group_list_item.dart';
import 'package:grex/features/groups/presentation/widgets/group_list_skeleton.dart';
import 'package:grex/features/payments/data/models/models.dart';
import 'package:grex/features/payments/data/models/payment_model.dart';
import 'package:grex/features/payments/data/repositories/repositories.dart';
import 'package:grex/features/payments/data/repositories/supabase_payment_repository.dart';
import 'package:grex/features/payments/domain/entities/entities.dart';
import 'package:grex/features/payments/domain/entities/payment.dart';
import 'package:grex/features/payments/domain/failures/failures.dart';
import 'package:grex/features/payments/domain/failures/payment_failure.dart';
import 'package:grex/features/payments/domain/repositories/payment_repository.dart';
import 'package:grex/features/payments/presentation/bloc/payment_bloc.dart';
import 'package:grex/features/payments/presentation/bloc/payment_event.dart';
import 'package:grex/features/payments/presentation/bloc/payment_state.dart';
import 'package:grex/features/payments/presentation/pages/create_payment_page.dart';
import 'package:grex/features/payments/presentation/pages/payment_list_page.dart';
import 'package:grex/features/payments/presentation/widgets/empty_payments_widget.dart';
import 'package:grex/features/payments/presentation/widgets/payment_filter_sheet.dart';
import 'package:grex/features/payments/presentation/widgets/payment_list_error_widget.dart';
import 'package:grex/features/payments/presentation/widgets/payment_list_item.dart';
import 'package:grex/features/payments/presentation/widgets/payment_list_skeleton.dart';
import 'package:grex/shared/accessibility/accessibility_constants.dart';
import 'package:grex/shared/accessibility/accessibility_helpers.dart';
import 'package:grex/shared/accessibility/accessibility_widgets.dart';
import 'package:grex/shared/accessibility/focus_announcer.dart';
import 'package:grex/shared/extensions/context_extensions.dart';
import 'package:grex/shared/extensions/datetime_extensions.dart';
import 'package:grex/shared/extensions/extensions.dart';
import 'package:grex/shared/extensions/string_extensions.dart';
import 'package:grex/shared/theme/app_colors.dart';
import 'package:grex/shared/theme/app_durations.dart';
import 'package:grex/shared/theme/app_elevation.dart';
import 'package:grex/shared/theme/app_fonts.dart';
import 'package:grex/shared/theme/app_icon_sizes.dart';
import 'package:grex/shared/theme/app_radius.dart';
import 'package:grex/shared/theme/app_spacing.dart';
import 'package:grex/shared/theme/app_text_styles.dart';
import 'package:grex/shared/theme/app_theme.dart';
import 'package:grex/shared/theme/design_tokens.dart';
import 'package:grex/shared/utils/currency_formatter.dart';
import 'package:grex/shared/utils/locale_defaults.dart';
import 'package:grex/shared/widgets/dev_logout_overlay.dart';
import 'package:grex/shared/widgets/group_currency_field.dart';
import 'package:grex/shared/widgets/language_switcher.dart';
import 'package:grex/shared/widgets/loading_indicator.dart';
import 'package:grex/shared/widgets/optimized_image.dart';
import 'package:grex/shared/widgets/optimized_list_view.dart';
import 'package:grex/shared/widgets/shimmer_box.dart';
import '../tool/coverage_aggregator.dart';

void main() {
  test('every library under lib/ is imported for coverage', () {
    final source = File(aggregatorPath).readAsStringSync();

    expect(
      declaredImports(source),
      equals(coverageEligibleLibraries()),
      reason:
          'The coverage aggregator is stale, so some libraries are missing '
          'from lcov.info and every layer percentage reads higher than the '
          'truth. Regenerate it with:\n'
          '  dart run tool/generate_coverage_aggregator.dart',
    );
  });
}
