// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/core/services/real_time_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:grex/core/services/real_time_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:realtime_client/src/constants.dart' as _i8;
import 'package:realtime_client/src/push.dart' as _i3;
import 'package:realtime_client/src/types.dart' as _i7;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRealtimeChannel_0 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePush_1 extends _i1.SmartFake implements _i3.Push {
  _FakePush_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimePresence_2 extends _i1.SmartFake
    implements _i2.RealtimePresence {
  _FakeRealtimePresence_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RealTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealTimeService extends _i1.Mock implements _i4.RealTimeService {
  MockRealTimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i4.ConnectionState> get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i5.Stream<_i4.ConnectionState>.empty(),
          )
          as _i5.Stream<_i4.ConnectionState>);

  @override
  _i2.RealtimeChannel subscribeToTable(
    String? table, {
    String? filter,
    void Function(Map<String, dynamic>)? onData,
    void Function(Object)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToTable,
              [table],
              {#filter: filter, #onData: onData, #onError: onError},
            ),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(
                #subscribeToTable,
                [table],
                {#filter: filter, #onData: onData, #onError: onError},
              ),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel subscribeToGroup(
    String? groupId,
    String? table, {
    void Function(Map<String, dynamic>)? onData,
    void Function(Object)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToGroup,
              [groupId, table],
              {#onData: onData, #onError: onError},
            ),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(
                #subscribeToGroup,
                [groupId, table],
                {#onData: onData, #onError: onError},
              ),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i5.Future<void> queueChange(_i4.QueuedChange? change) =>
      (super.noSuchMethod(
            Invocation.method(#queueChange, [change]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i4.QueuedChange> getQueuedChanges() =>
      (super.noSuchMethod(
            Invocation.method(#getQueuedChanges, []),
            returnValue: <_i4.QueuedChange>[],
          )
          as List<_i4.QueuedChange>);

  @override
  _i5.Future<void> clearQueuedChanges() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueuedChanges, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> syncQueuedChanges() =>
      (super.noSuchMethod(
            Invocation.method(#syncQueuedChanges, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RealtimeChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeChannel extends _i1.Mock implements _i2.RealtimeChannel {
  MockRealtimeChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get joinedOnce =>
      (super.noSuchMethod(Invocation.getter(#joinedOnce), returnValue: false)
          as bool);

  @override
  _i3.Push get joinPush =>
      (super.noSuchMethod(
            Invocation.getter(#joinPush),
            returnValue: _FakePush_1(this, Invocation.getter(#joinPush)),
          )
          as _i3.Push);

  @override
  _i2.RealtimePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeRealtimePresence_2(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i2.RealtimePresence);

  @override
  String get broadcastEndpointURL =>
      (super.noSuchMethod(
            Invocation.getter(#broadcastEndpointURL),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#broadcastEndpointURL),
            ),
          )
          as String);

  @override
  String get subTopic =>
      (super.noSuchMethod(
            Invocation.getter(#subTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#subTopic),
            ),
          )
          as String);

  @override
  String get topic =>
      (super.noSuchMethod(
            Invocation.getter(#topic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get params =>
      (super.noSuchMethod(
            Invocation.getter(#params),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.RealtimeClient get socket =>
      (super.noSuchMethod(
            Invocation.getter(#socket),
            returnValue: _FakeRealtimeClient_3(
              this,
              Invocation.getter(#socket),
            ),
          )
          as _i2.RealtimeClient);

  @override
  bool get canPush =>
      (super.noSuchMethod(Invocation.getter(#canPush), returnValue: false)
          as bool);

  @override
  String get joinRef =>
      (super.noSuchMethod(
            Invocation.getter(#joinRef),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#joinRef),
            ),
          )
          as String);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get isErrored =>
      (super.noSuchMethod(Invocation.getter(#isErrored), returnValue: false)
          as bool);

  @override
  bool get isJoined =>
      (super.noSuchMethod(Invocation.getter(#isJoined), returnValue: false)
          as bool);

  @override
  bool get isJoining =>
      (super.noSuchMethod(Invocation.getter(#isJoining), returnValue: false)
          as bool);

  @override
  bool get isLeaving =>
      (super.noSuchMethod(Invocation.getter(#isLeaving), returnValue: false)
          as bool);

  @override
  set joinedOnce(bool? value) => super.noSuchMethod(
    Invocation.setter(#joinedOnce, value),
    returnValueForMissingStub: null,
  );

  @override
  set joinPush(_i3.Push? value) => super.noSuchMethod(
    Invocation.setter(#joinPush, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i2.RealtimePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set broadcastEndpointURL(String? value) => super.noSuchMethod(
    Invocation.setter(#broadcastEndpointURL, value),
    returnValueForMissingStub: null,
  );

  @override
  set params(Map<String, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#params, value),
    returnValueForMissingStub: null,
  );

  @override
  void rejoinUntilConnected() => super.noSuchMethod(
    Invocation.method(#rejoinUntilConnected, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RealtimeChannel subscribe([
    void Function(_i2.RealtimeSubscribeStatus, Object?)? callback,
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [callback, timeout]),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#subscribe, [callback, timeout]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  List<_i2.SinglePresenceState> presenceState() =>
      (super.noSuchMethod(
            Invocation.method(#presenceState, []),
            returnValue: <_i2.SinglePresenceState>[],
          )
          as List<_i2.SinglePresenceState>);

  @override
  _i5.Future<_i2.ChannelResponse> track(
    Map<String, dynamic>? payload, [
    Map<String, dynamic>? opts = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#track, [payload, opts]),
            returnValue: _i5.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i5.Future<_i2.ChannelResponse>);

  @override
  _i5.Future<_i2.ChannelResponse> untrack([
    Map<String, dynamic>? opts = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#untrack, [opts]),
            returnValue: _i5.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i5.Future<_i2.ChannelResponse>);

  @override
  _i2.RealtimeChannel onPostgresChanges({
    required _i2.PostgresChangeEvent? event,
    String? schema,
    String? table,
    _i2.PostgresChangeFilter? filter,
    required void Function(_i2.PostgresChangePayload)? callback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onPostgresChanges, [], {
              #event: event,
              #schema: schema,
              #table: table,
              #filter: filter,
              #callback: callback,
            }),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#onPostgresChanges, [], {
                #event: event,
                #schema: schema,
                #table: table,
                #filter: filter,
                #callback: callback,
              }),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onBroadcast({
    required String? event,
    required void Function(Map<String, dynamic>)? callback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onBroadcast, [], {
              #event: event,
              #callback: callback,
            }),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#onBroadcast, [], {
                #event: event,
                #callback: callback,
              }),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onPresenceSync(
    void Function(_i2.RealtimePresenceSyncPayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceSync, [callback]),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#onPresenceSync, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onPresenceJoin(
    void Function(_i2.RealtimePresenceJoinPayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceJoin, [callback]),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#onPresenceJoin, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onPresenceLeave(
    void Function(_i2.RealtimePresenceLeavePayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceLeave, [callback]),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#onPresenceLeave, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onSystemEvents(void Function(dynamic)? callback) =>
      (super.noSuchMethod(
            Invocation.method(#onSystemEvents, [callback]),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#onSystemEvents, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onEvents(
    String? type,
    _i7.ChannelFilter? filter,
    _i2.BindingCallback? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onEvents, [type, filter, callback]),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#onEvents, [type, filter, callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel off(String? type, Map<String, String>? filter) =>
      (super.noSuchMethod(
            Invocation.method(#off, [type, filter]),
            returnValue: _FakeRealtimeChannel_0(
              this,
              Invocation.method(#off, [type, filter]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i3.Push push(
    _i8.ChannelEvents? event,
    Map<String, dynamic>? payload, [
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#push, [event, payload, timeout]),
            returnValue: _FakePush_1(
              this,
              Invocation.method(#push, [event, payload, timeout]),
            ),
          )
          as _i3.Push);

  @override
  _i5.Future<_i2.ChannelResponse> sendBroadcastMessage({
    required String? event,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendBroadcastMessage, [], {
              #event: event,
              #payload: payload,
            }),
            returnValue: _i5.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i5.Future<_i2.ChannelResponse>);

  @override
  _i5.Future<_i2.ChannelResponse> send({
    required _i7.RealtimeListenTypes? type,
    String? event,
    required Map<String, dynamic>? payload,
    Map<String, dynamic>? opts = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#send, [], {
              #type: type,
              #event: event,
              #payload: payload,
              #opts: opts,
            }),
            returnValue: _i5.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i5.Future<_i2.ChannelResponse>);

  @override
  void updateJoinPayload(Map<String, dynamic>? payload) => super.noSuchMethod(
    Invocation.method(#updateJoinPayload, [payload]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String> unsubscribe([Duration? timeout]) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [timeout]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#unsubscribe, [timeout]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  dynamic onMessage(String? event, dynamic payload, [String? ref]) =>
      super.noSuchMethod(Invocation.method(#onMessage, [event, payload, ref]));

  @override
  bool isMember(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#isMember, [topic]),
            returnValue: false,
          )
          as bool);

  @override
  void rejoin([Duration? timeout]) => super.noSuchMethod(
    Invocation.method(#rejoin, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  void forceRejoin([Duration? timeout]) => super.noSuchMethod(
    Invocation.method(#forceRejoin, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  void trigger(String? type, [dynamic payload, String? ref]) =>
      super.noSuchMethod(
        Invocation.method(#trigger, [type, payload, ref]),
        returnValueForMissingStub: null,
      );

  @override
  String replyEventName(String? ref) =>
      (super.noSuchMethod(
            Invocation.method(#replyEventName, [ref]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#replyEventName, [ref]),
            ),
          )
          as String);
}
