// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/core/services/real_time_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:grex/core/services/offline_queue_storage.dart' as _i8;
import 'package:grex/core/services/real_time_service.dart' as _i9;
import 'package:logging/logging.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:realtime_client/src/constants.dart' as _i11;
import 'package:realtime_client/src/message.dart' as _i13;
import 'package:realtime_client/src/push.dart' as _i3;
import 'package:realtime_client/src/retry_timer.dart' as _i5;
import 'package:realtime_client/src/types.dart' as _i10;
import 'package:supabase/supabase.dart' as _i2;
import 'package:web_socket_channel/web_socket_channel.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFunctionsClient_0 extends _i1.SmartFake
    implements _i2.FunctionsClient {
  _FakeFunctionsClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_1 extends _i1.SmartFake
    implements _i2.SupabaseStorageClient {
  _FakeSupabaseStorageClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_2 extends _i1.SmartFake
    implements _i2.RealtimeClient {
  _FakeRealtimeClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_3 extends _i1.SmartFake
    implements _i2.PostgrestClient {
  _FakePostgrestClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_4 extends _i1.SmartFake implements _i2.GoTrueClient {
  _FakeGoTrueClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
    implements _i2.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_6 extends _i1.SmartFake
    implements _i2.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_7<T1> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_8 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePush_9 extends _i1.SmartFake implements _i3.Push {
  _FakePush_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimePresence_10 extends _i1.SmartFake
    implements _i2.RealtimePresence {
  _FakeRealtimePresence_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_11 extends _i1.SmartFake implements Duration {
  _FakeDuration_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebSocketChannel_12 extends _i1.SmartFake
    implements _i4.WebSocketChannel {
  _FakeWebSocketChannel_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRetryTimer_13 extends _i1.SmartFake implements _i5.RetryTimer {
  _FakeRetryTimer_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStreamFilterBuilder_14 extends _i1.SmartFake
    implements _i2.SupabaseStreamFilterBuilder {
  _FakeSupabaseStreamFilterBuilder_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePostgrestQueryBuilder_15<T> extends _i1.SmartFake
    implements _i2.PostgrestQueryBuilder<T> {
  _FakePostgrestQueryBuilder_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestBuilder_16<T, S, R> extends _i1.SmartFake
    implements _i2.PostgrestBuilder<T, S, R> {
  _FakePostgrestBuilder_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_17 extends _i1.SmartFake implements Uri {
  _FakeUri_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_18<T> extends _i1.SmartFake implements _i6.Future<T> {
  _FakeFuture_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestTransformBuilder_19<T> extends _i1.SmartFake
    implements _i2.PostgrestTransformBuilder<T> {
  _FakePostgrestTransformBuilder_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponsePostgrestBuilder_20<T, S, R> extends _i1.SmartFake
    implements _i2.ResponsePostgrestBuilder<T, S, R> {
  _FakeResponsePostgrestBuilder_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i2.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_0(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i2.FunctionsClient);

  @override
  _i2.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_1(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.SupabaseStorageClient);

  @override
  _i2.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i2.RealtimeClient);

  @override
  _i2.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_3(this, Invocation.getter(#rest)),
          )
          as _i2.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i2.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_4(this, Invocation.getter(#auth)),
          )
          as _i2.GoTrueClient);

  @override
  set functions(_i2.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i2.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i2.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i2.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_5(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i2.SupabaseQueryBuilder);

  @override
  _i2.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_6(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i2.SupabaseQuerySchema);

  @override
  _i2.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_7<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i2.PostgrestFilterBuilder<T>);

  @override
  _i2.RealtimeChannel channel(
    String? name, {
    _i2.RealtimeChannelConfig? opts = const _i2.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  List<_i2.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  _i6.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [OfflineQueueStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineQueueStorage extends _i1.Mock
    implements _i8.OfflineQueueStorage {
  MockOfflineQueueStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveQueuedChanges(List<_i9.QueuedChange>? changes) =>
      (super.noSuchMethod(
            Invocation.method(#saveQueuedChanges, [changes]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.QueuedChange>> loadQueuedChanges() =>
      (super.noSuchMethod(
            Invocation.method(#loadQueuedChanges, []),
            returnValue: _i6.Future<List<_i9.QueuedChange>>.value(
              <_i9.QueuedChange>[],
            ),
          )
          as _i6.Future<List<_i9.QueuedChange>>);

  @override
  _i6.Future<void> clearQueuedChanges() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueuedChanges, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeQueuedChanges(List<String>? changeIds) =>
      (super.noSuchMethod(
            Invocation.method(#removeQueuedChanges, [changeIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [RealtimeChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeChannel extends _i1.Mock implements _i2.RealtimeChannel {
  MockRealtimeChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get joinedOnce =>
      (super.noSuchMethod(Invocation.getter(#joinedOnce), returnValue: false)
          as bool);

  @override
  _i3.Push get joinPush =>
      (super.noSuchMethod(
            Invocation.getter(#joinPush),
            returnValue: _FakePush_9(this, Invocation.getter(#joinPush)),
          )
          as _i3.Push);

  @override
  _i2.RealtimePresence get presence =>
      (super.noSuchMethod(
            Invocation.getter(#presence),
            returnValue: _FakeRealtimePresence_10(
              this,
              Invocation.getter(#presence),
            ),
          )
          as _i2.RealtimePresence);

  @override
  String get broadcastEndpointURL =>
      (super.noSuchMethod(
            Invocation.getter(#broadcastEndpointURL),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#broadcastEndpointURL),
            ),
          )
          as String);

  @override
  String get subTopic =>
      (super.noSuchMethod(
            Invocation.getter(#subTopic),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#subTopic),
            ),
          )
          as String);

  @override
  String get topic =>
      (super.noSuchMethod(
            Invocation.getter(#topic),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get params =>
      (super.noSuchMethod(
            Invocation.getter(#params),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.RealtimeClient get socket =>
      (super.noSuchMethod(
            Invocation.getter(#socket),
            returnValue: _FakeRealtimeClient_2(
              this,
              Invocation.getter(#socket),
            ),
          )
          as _i2.RealtimeClient);

  @override
  bool get canPush =>
      (super.noSuchMethod(Invocation.getter(#canPush), returnValue: false)
          as bool);

  @override
  String get joinRef =>
      (super.noSuchMethod(
            Invocation.getter(#joinRef),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#joinRef),
            ),
          )
          as String);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get isErrored =>
      (super.noSuchMethod(Invocation.getter(#isErrored), returnValue: false)
          as bool);

  @override
  bool get isJoined =>
      (super.noSuchMethod(Invocation.getter(#isJoined), returnValue: false)
          as bool);

  @override
  bool get isJoining =>
      (super.noSuchMethod(Invocation.getter(#isJoining), returnValue: false)
          as bool);

  @override
  bool get isLeaving =>
      (super.noSuchMethod(Invocation.getter(#isLeaving), returnValue: false)
          as bool);

  @override
  set joinedOnce(bool? value) => super.noSuchMethod(
    Invocation.setter(#joinedOnce, value),
    returnValueForMissingStub: null,
  );

  @override
  set joinPush(_i3.Push? value) => super.noSuchMethod(
    Invocation.setter(#joinPush, value),
    returnValueForMissingStub: null,
  );

  @override
  set presence(_i2.RealtimePresence? value) => super.noSuchMethod(
    Invocation.setter(#presence, value),
    returnValueForMissingStub: null,
  );

  @override
  set broadcastEndpointURL(String? value) => super.noSuchMethod(
    Invocation.setter(#broadcastEndpointURL, value),
    returnValueForMissingStub: null,
  );

  @override
  set params(Map<String, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#params, value),
    returnValueForMissingStub: null,
  );

  @override
  void rejoinUntilConnected() => super.noSuchMethod(
    Invocation.method(#rejoinUntilConnected, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RealtimeChannel subscribe([
    void Function(_i2.RealtimeSubscribeStatus, Object?)? callback,
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [callback, timeout]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#subscribe, [callback, timeout]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  List<_i2.SinglePresenceState> presenceState() =>
      (super.noSuchMethod(
            Invocation.method(#presenceState, []),
            returnValue: <_i2.SinglePresenceState>[],
          )
          as List<_i2.SinglePresenceState>);

  @override
  _i6.Future<_i2.ChannelResponse> track(
    Map<String, dynamic>? payload, [
    Map<String, dynamic>? opts = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#track, [payload, opts]),
            returnValue: _i6.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i2.ChannelResponse>);

  @override
  _i6.Future<_i2.ChannelResponse> untrack([
    Map<String, dynamic>? opts = const {},
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#untrack, [opts]),
            returnValue: _i6.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i2.ChannelResponse>);

  @override
  _i2.RealtimeChannel onPostgresChanges({
    required _i2.PostgresChangeEvent? event,
    String? schema,
    String? table,
    _i2.PostgresChangeFilter? filter,
    required void Function(_i2.PostgresChangePayload)? callback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onPostgresChanges, [], {
              #event: event,
              #schema: schema,
              #table: table,
              #filter: filter,
              #callback: callback,
            }),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPostgresChanges, [], {
                #event: event,
                #schema: schema,
                #table: table,
                #filter: filter,
                #callback: callback,
              }),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onBroadcast({
    required String? event,
    required void Function(Map<String, dynamic>)? callback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onBroadcast, [], {
              #event: event,
              #callback: callback,
            }),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onBroadcast, [], {
                #event: event,
                #callback: callback,
              }),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onPresenceSync(
    void Function(_i2.RealtimePresenceSyncPayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceSync, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceSync, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onPresenceJoin(
    void Function(_i2.RealtimePresenceJoinPayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceJoin, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceJoin, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onPresenceLeave(
    void Function(_i2.RealtimePresenceLeavePayload)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onPresenceLeave, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onPresenceLeave, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onSystemEvents(void Function(dynamic)? callback) =>
      (super.noSuchMethod(
            Invocation.method(#onSystemEvents, [callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onSystemEvents, [callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel onEvents(
    String? type,
    _i10.ChannelFilter? filter,
    _i2.BindingCallback? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onEvents, [type, filter, callback]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#onEvents, [type, filter, callback]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i2.RealtimeChannel off(String? type, Map<String, String>? filter) =>
      (super.noSuchMethod(
            Invocation.method(#off, [type, filter]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#off, [type, filter]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  _i3.Push push(
    _i11.ChannelEvents? event,
    Map<String, dynamic>? payload, [
    Duration? timeout,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#push, [event, payload, timeout]),
            returnValue: _FakePush_9(
              this,
              Invocation.method(#push, [event, payload, timeout]),
            ),
          )
          as _i3.Push);

  @override
  _i6.Future<_i2.ChannelResponse> sendBroadcastMessage({
    required String? event,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendBroadcastMessage, [], {
              #event: event,
              #payload: payload,
            }),
            returnValue: _i6.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i2.ChannelResponse>);

  @override
  _i6.Future<_i2.ChannelResponse> send({
    required _i10.RealtimeListenTypes? type,
    String? event,
    required Map<String, dynamic>? payload,
    Map<String, dynamic>? opts = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#send, [], {
              #type: type,
              #event: event,
              #payload: payload,
              #opts: opts,
            }),
            returnValue: _i6.Future<_i2.ChannelResponse>.value(
              _i2.ChannelResponse.ok,
            ),
          )
          as _i6.Future<_i2.ChannelResponse>);

  @override
  void updateJoinPayload(Map<String, dynamic>? payload) => super.noSuchMethod(
    Invocation.method(#updateJoinPayload, [payload]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<String> unsubscribe([Duration? timeout]) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [timeout]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#unsubscribe, [timeout]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  dynamic onMessage(String? event, dynamic payload, [String? ref]) =>
      super.noSuchMethod(Invocation.method(#onMessage, [event, payload, ref]));

  @override
  bool isMember(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#isMember, [topic]),
            returnValue: false,
          )
          as bool);

  @override
  void rejoin([Duration? timeout]) => super.noSuchMethod(
    Invocation.method(#rejoin, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  void forceRejoin([Duration? timeout]) => super.noSuchMethod(
    Invocation.method(#forceRejoin, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  void trigger(String? type, [dynamic payload, String? ref]) =>
      super.noSuchMethod(
        Invocation.method(#trigger, [type, payload, ref]),
        returnValueForMissingStub: null,
      );

  @override
  String replyEventName(String? ref) =>
      (super.noSuchMethod(
            Invocation.method(#replyEventName, [ref]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#replyEventName, [ref]),
            ),
          )
          as String);
}

/// A class which mocks [RealtimeClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeClient extends _i1.Mock implements _i2.RealtimeClient {
  MockRealtimeClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.RealtimeChannel> get channels =>
      (super.noSuchMethod(
            Invocation.getter(#channels),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  String get endPoint =>
      (super.noSuchMethod(
            Invocation.getter(#endPoint),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#endPoint),
            ),
          )
          as String);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, dynamic> get params =>
      (super.noSuchMethod(
            Invocation.getter(#params),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_11(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  _i2.WebSocketTransport get transport =>
      (super.noSuchMethod(
            Invocation.getter(#transport),
            returnValue: (String url, Map<String, String> headers) =>
                _FakeWebSocketChannel_12(this, Invocation.getter(#transport)),
          )
          as _i2.WebSocketTransport);

  @override
  int get heartbeatIntervalMs =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeatIntervalMs),
            returnValue: 0,
          )
          as int);

  @override
  int get ref =>
      (super.noSuchMethod(Invocation.getter(#ref), returnValue: 0) as int);

  @override
  _i5.RetryTimer get reconnectTimer =>
      (super.noSuchMethod(
            Invocation.getter(#reconnectTimer),
            returnValue: _FakeRetryTimer_13(
              this,
              Invocation.getter(#reconnectTimer),
            ),
          )
          as _i5.RetryTimer);

  @override
  _i2.RealtimeEncode get encode =>
      (super.noSuchMethod(
            Invocation.getter(#encode),
            returnValue: (dynamic payload, void Function(String) callback) {},
          )
          as _i2.RealtimeEncode);

  @override
  _i2.RealtimeDecode get decode =>
      (super.noSuchMethod(
            Invocation.getter(#decode),
            returnValue: (String payload, void Function(dynamic) callback) {},
          )
          as _i2.RealtimeDecode);

  @override
  _i5.TimerCalculation get reconnectAfterMs =>
      (super.noSuchMethod(
            Invocation.getter(#reconnectAfterMs),
            returnValue: (int tries) => 0,
          )
          as _i5.TimerCalculation);

  @override
  List<dynamic> get sendBuffer =>
      (super.noSuchMethod(
            Invocation.getter(#sendBuffer),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Map<String, List<Function>> get stateChangeCallbacks =>
      (super.noSuchMethod(
            Invocation.getter(#stateChangeCallbacks),
            returnValue: <String, List<Function>>{},
          )
          as Map<String, List<Function>>);

  @override
  int get longpollerTimeout =>
      (super.noSuchMethod(Invocation.getter(#longpollerTimeout), returnValue: 0)
          as int);

  @override
  String get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#connectionState),
            ),
          )
          as String);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  String get endPointURL =>
      (super.noSuchMethod(
            Invocation.getter(#endPointURL),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#endPointURL),
            ),
          )
          as String);

  @override
  set accessToken(String? value) => super.noSuchMethod(
    Invocation.setter(#accessToken, value),
    returnValueForMissingStub: null,
  );

  @override
  set channels(List<_i2.RealtimeChannel>? value) => super.noSuchMethod(
    Invocation.setter(#channels, value),
    returnValueForMissingStub: null,
  );

  @override
  set heartbeatIntervalMs(int? value) => super.noSuchMethod(
    Invocation.setter(#heartbeatIntervalMs, value),
    returnValueForMissingStub: null,
  );

  @override
  set heartbeatTimer(_i6.Timer? value) => super.noSuchMethod(
    Invocation.setter(#heartbeatTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set pendingHeartbeatRef(String? value) => super.noSuchMethod(
    Invocation.setter(#pendingHeartbeatRef, value),
    returnValueForMissingStub: null,
  );

  @override
  set ref(int? value) => super.noSuchMethod(
    Invocation.setter(#ref, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnectTimer(_i5.RetryTimer? value) => super.noSuchMethod(
    Invocation.setter(#reconnectTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set logger(void Function(String?, String?, dynamic)? value) =>
      super.noSuchMethod(
        Invocation.setter(#logger, value),
        returnValueForMissingStub: null,
      );

  @override
  set encode(_i2.RealtimeEncode? value) => super.noSuchMethod(
    Invocation.setter(#encode, value),
    returnValueForMissingStub: null,
  );

  @override
  set decode(_i2.RealtimeDecode? value) => super.noSuchMethod(
    Invocation.setter(#decode, value),
    returnValueForMissingStub: null,
  );

  @override
  set reconnectAfterMs(_i5.TimerCalculation? value) => super.noSuchMethod(
    Invocation.setter(#reconnectAfterMs, value),
    returnValueForMissingStub: null,
  );

  @override
  set conn(_i4.WebSocketChannel? value) => super.noSuchMethod(
    Invocation.setter(#conn, value),
    returnValueForMissingStub: null,
  );

  @override
  set sendBuffer(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#sendBuffer, value),
    returnValueForMissingStub: null,
  );

  @override
  set stateChangeCallbacks(Map<String, List<Function>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#stateChangeCallbacks, value),
        returnValueForMissingStub: null,
      );

  @override
  set longpollerTimeout(int? value) => super.noSuchMethod(
    Invocation.setter(#longpollerTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set connState(_i2.SocketStates? value) => super.noSuchMethod(
    Invocation.setter(#connState, value),
    returnValueForMissingStub: null,
  );

  @override
  set customAccessToken(_i6.Future<String?> Function()? value) =>
      super.noSuchMethod(
        Invocation.setter(#customAccessToken, value),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnect({int? code, String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [], {#code: code, #reason: reason}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  List<_i2.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i2.RealtimeChannel>[],
          )
          as List<_i2.RealtimeChannel>);

  @override
  _i6.Future<String> removeChannel(_i2.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  void log([
    String? kind,
    String? msg,
    dynamic data,
    _i12.Level? level = _i12.Level.FINEST,
  ]) => super.noSuchMethod(
    Invocation.method(#log, [kind, msg, data, level]),
    returnValueForMissingStub: null,
  );

  @override
  void onOpen(void Function()? callback) => super.noSuchMethod(
    Invocation.method(#onOpen, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void onClose(void Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onClose, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(void Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onError, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void onMessage(void Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onMessage, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void remove(_i2.RealtimeChannel? channel) => super.noSuchMethod(
    Invocation.method(#remove, [channel]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RealtimeChannel channel(
    String? topic, [
    _i2.RealtimeChannelConfig? params = const _i2.RealtimeChannelConfig(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [topic, params]),
            returnValue: _FakeRealtimeChannel_8(
              this,
              Invocation.method(#channel, [topic, params]),
            ),
          )
          as _i2.RealtimeChannel);

  @override
  String? push(_i13.Message? message) =>
      (super.noSuchMethod(Invocation.method(#push, [message])) as String?);

  @override
  void onConnMessage(String? rawMessage) => super.noSuchMethod(
    Invocation.method(#onConnMessage, [rawMessage]),
    returnValueForMissingStub: null,
  );

  @override
  String makeRef() =>
      (super.noSuchMethod(
            Invocation.method(#makeRef, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#makeRef, []),
            ),
          )
          as String);

  @override
  _i6.Future<void> setAuth(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setAuth, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void leaveOpenTopic(String? topic) => super.noSuchMethod(
    Invocation.method(#leaveOpenTopic, [topic]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> sendHeartbeat() =>
      (super.noSuchMethod(
            Invocation.method(#sendHeartbeat, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SupabaseQueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseQueryBuilder extends _i1.Mock
    implements _i2.SupabaseQueryBuilder {
  MockSupabaseQueryBuilder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseStreamFilterBuilder stream({required List<String>? primaryKey}) =>
      (super.noSuchMethod(
            Invocation.method(#stream, [], {#primaryKey: primaryKey}),
            returnValue: _FakeSupabaseStreamFilterBuilder_14(
              this,
              Invocation.method(#stream, [], {#primaryKey: primaryKey}),
            ),
          )
          as _i2.SupabaseStreamFilterBuilder);

  @override
  _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestFilterBuilder_7<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> insert(
    Object? values, {
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [values],
              {#defaultToNull: defaultToNull},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #insert,
                [values],
                {#defaultToNull: defaultToNull},
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> upsert(
    Object? values, {
    String? onConflict,
    bool? ignoreDuplicates = false,
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsert,
              [values],
              {
                #onConflict: onConflict,
                #ignoreDuplicates: ignoreDuplicates,
                #defaultToNull: defaultToNull,
              },
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #upsert,
                [values],
                {
                  #onConflict: onConflict,
                  #ignoreDuplicates: ignoreDuplicates,
                  #defaultToNull: defaultToNull,
                },
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> update(Map<dynamic, dynamic>? values) =>
      (super.noSuchMethod(
            Invocation.method(#update, [values]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#update, [values]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#delete, []),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<int> count([
    _i2.CountOption? option = _i2.CountOption.exact,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [option]),
            returnValue: _FakePostgrestFilterBuilder_7<int>(
              this,
              Invocation.method(#count, [option]),
            ),
          )
          as _i2.PostgrestFilterBuilder<int>);

  @override
  _i2.PostgrestQueryBuilder<dynamic> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestQueryBuilder_15<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i2.PostgrestQueryBuilder<dynamic>);

  @override
  _i2.PostgrestBuilder<U, U, dynamic> withConverter<U>(
    _i2.PostgrestConverter<U, dynamic>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_16<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i2.PostgrestBuilder<U, U, dynamic>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_17(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_17(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i6.Stream<dynamic> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i6.Stream<dynamic>.empty(),
          )
          as _i6.Stream<dynamic>);

  @override
  _i6.Future<dynamic> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<U> then<U>(
    _i6.FutureOr<U> Function(dynamic)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i6.Future<U>.value(v),
                ) ??
                _FakeFuture_18<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i6.Future<U>);

  @override
  _i6.Future<dynamic> timeout(
    Duration? timeLimit, {
    _i6.FutureOr<dynamic> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> whenComplete(_i6.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}

/// A class which mocks [PostgrestQueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgrestQueryBuilderRealTime extends _i1.Mock
    implements _i2.PostgrestQueryBuilder<dynamic> {
  MockPostgrestQueryBuilderRealTime() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestFilterBuilder_7<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> insert(
    Object? values, {
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [values],
              {#defaultToNull: defaultToNull},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #insert,
                [values],
                {#defaultToNull: defaultToNull},
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> upsert(
    Object? values, {
    String? onConflict,
    bool? ignoreDuplicates = false,
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsert,
              [values],
              {
                #onConflict: onConflict,
                #ignoreDuplicates: ignoreDuplicates,
                #defaultToNull: defaultToNull,
              },
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #upsert,
                [values],
                {
                  #onConflict: onConflict,
                  #ignoreDuplicates: ignoreDuplicates,
                  #defaultToNull: defaultToNull,
                },
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> update(Map<dynamic, dynamic>? values) =>
      (super.noSuchMethod(
            Invocation.method(#update, [values]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#update, [values]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#delete, []),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<int> count([
    _i2.CountOption? option = _i2.CountOption.exact,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [option]),
            returnValue: _FakePostgrestFilterBuilder_7<int>(
              this,
              Invocation.method(#count, [option]),
            ),
          )
          as _i2.PostgrestFilterBuilder<int>);

  @override
  _i2.PostgrestQueryBuilder<dynamic> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestQueryBuilder_15<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i2.PostgrestQueryBuilder<dynamic>);

  @override
  _i2.PostgrestBuilder<U, U, dynamic> withConverter<U>(
    _i2.PostgrestConverter<U, dynamic>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_16<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i2.PostgrestBuilder<U, U, dynamic>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_17(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_17(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i6.Stream<dynamic> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i6.Stream<dynamic>.empty(),
          )
          as _i6.Stream<dynamic>);

  @override
  _i6.Future<dynamic> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<U> then<U>(
    _i6.FutureOr<U> Function(dynamic)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i6.Future<U>.value(v),
                ) ??
                _FakeFuture_18<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i6.Future<U>);

  @override
  _i6.Future<dynamic> timeout(
    Duration? timeLimit, {
    _i6.FutureOr<dynamic> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> whenComplete(_i6.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}

/// A class which mocks [PostgrestFilterBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgrestFilterBuilderRealTime extends _i1.Mock
    implements _i2.PostgrestFilterBuilder<dynamic> {
  MockPostgrestFilterBuilderRealTime() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostgrestFilterBuilder<dynamic> copyWithUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#copyWithUrl, [url]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#copyWithUrl, [url]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> not(
    String? column,
    String? operator,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#not, [column, operator, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#not, [column, operator, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> or(
    String? filters, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #or,
              [filters],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #or,
                [filters],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> eq(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#eq, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#eq, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> neq(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#neq, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#neq, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> gt(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#gt, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#gt, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> gte(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#gte, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#gte, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> lt(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#lt, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#lt, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> lte(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#lte, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#lte, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> like(String? column, String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#like, [column, pattern]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#like, [column, pattern]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> likeAllOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeAllOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#likeAllOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> likeAnyOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeAnyOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#likeAnyOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> ilike(String? column, String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#ilike, [column, pattern]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#ilike, [column, pattern]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> ilikeAllOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ilikeAllOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#ilikeAllOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> ilikeAnyOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ilikeAnyOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#ilikeAnyOf, [column, patterns]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> isFilter(String? column, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#isFilter, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#isFilter, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> inFilter(
    String? column,
    List<dynamic>? values,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inFilter, [column, values]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#inFilter, [column, values]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> contains(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#contains, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> containedBy(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#containedBy, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#containedBy, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> rangeLt(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeLt, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#rangeLt, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> rangeGt(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeGt, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#rangeGt, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> rangeGte(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeGte, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#rangeGte, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> rangeLte(String? column, String? range) =>
      (super.noSuchMethod(
            Invocation.method(#rangeLte, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#rangeLte, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> rangeAdjacent(
    String? column,
    String? range,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rangeAdjacent, [column, range]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#rangeAdjacent, [column, range]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> overlaps(String? column, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#overlaps, [column, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#overlaps, [column, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> textSearch(
    String? column,
    String? query, {
    String? config,
    _i2.TextSearchType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #textSearch,
              [column, query],
              {#config: config, #type: type},
            ),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(
                #textSearch,
                [column, query],
                {#config: config, #type: type},
              ),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> filter(
    String? column,
    String? operator,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filter, [column, operator, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#filter, [column, operator, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> match(Map<String, Object>? query) =>
      (super.noSuchMethod(
            Invocation.method(#match, [query]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#match, [query]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestFilterBuilder_7<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i2.PostgrestTransformBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestTransformBuilder_19<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i2.PostgrestTransformBuilder<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestTransformBuilder<dynamic> order(
    String? column, {
    bool? ascending = false,
    bool? nullsFirst = false,
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #order,
              [column],
              {
                #ascending: ascending,
                #nullsFirst: nullsFirst,
                #referencedTable: referencedTable,
              },
            ),
            returnValue: _FakePostgrestTransformBuilder_19<dynamic>(
              this,
              Invocation.method(
                #order,
                [column],
                {
                  #ascending: ascending,
                  #nullsFirst: nullsFirst,
                  #referencedTable: referencedTable,
                },
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<dynamic>);

  @override
  _i2.PostgrestTransformBuilder<dynamic> limit(
    int? count, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #limit,
              [count],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestTransformBuilder_19<dynamic>(
              this,
              Invocation.method(
                #limit,
                [count],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<dynamic>);

  @override
  _i2.PostgrestTransformBuilder<dynamic> range(
    int? from,
    int? to, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #range,
              [from, to],
              {#referencedTable: referencedTable},
            ),
            returnValue: _FakePostgrestTransformBuilder_19<dynamic>(
              this,
              Invocation.method(
                #range,
                [from, to],
                {#referencedTable: referencedTable},
              ),
            ),
          )
          as _i2.PostgrestTransformBuilder<dynamic>);

  @override
  _i2.PostgrestTransformBuilder<Map<String, dynamic>> single() =>
      (super.noSuchMethod(
            Invocation.method(#single, []),
            returnValue:
                _FakePostgrestTransformBuilder_19<Map<String, dynamic>>(
                  this,
                  Invocation.method(#single, []),
                ),
          )
          as _i2.PostgrestTransformBuilder<Map<String, dynamic>>);

  @override
  _i2.PostgrestTransformBuilder<Map<String, dynamic>?> maybeSingle() =>
      (super.noSuchMethod(
            Invocation.method(#maybeSingle, []),
            returnValue:
                _FakePostgrestTransformBuilder_19<Map<String, dynamic>?>(
                  this,
                  Invocation.method(#maybeSingle, []),
                ),
          )
          as _i2.PostgrestTransformBuilder<Map<String, dynamic>?>);

  @override
  _i2.PostgrestTransformBuilder<String> csv() =>
      (super.noSuchMethod(
            Invocation.method(#csv, []),
            returnValue: _FakePostgrestTransformBuilder_19<String>(
              this,
              Invocation.method(#csv, []),
            ),
          )
          as _i2.PostgrestTransformBuilder<String>);

  @override
  _i2.ResponsePostgrestBuilder<_i2.PostgrestResponse<dynamic>, dynamic, dynamic>
  count([_i2.CountOption? count = _i2.CountOption.exact]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [count]),
            returnValue:
                _FakeResponsePostgrestBuilder_20<
                  _i2.PostgrestResponse<dynamic>,
                  dynamic,
                  dynamic
                >(this, Invocation.method(#count, [count])),
          )
          as _i2.ResponsePostgrestBuilder<
            _i2.PostgrestResponse<dynamic>,
            dynamic,
            dynamic
          >);

  @override
  _i2.PostgrestBuilder<void, void, void> head() =>
      (super.noSuchMethod(
            Invocation.method(#head, []),
            returnValue: _FakePostgrestBuilder_16<void, void, void>(
              this,
              Invocation.method(#head, []),
            ),
          )
          as _i2.PostgrestBuilder<void, void, void>);

  @override
  _i2.ResponsePostgrestBuilder<
    Map<String, dynamic>,
    Map<String, dynamic>,
    Map<String, dynamic>
  >
  geojson() =>
      (super.noSuchMethod(
            Invocation.method(#geojson, []),
            returnValue:
                _FakeResponsePostgrestBuilder_20<
                  Map<String, dynamic>,
                  Map<String, dynamic>,
                  Map<String, dynamic>
                >(this, Invocation.method(#geojson, [])),
          )
          as _i2.ResponsePostgrestBuilder<
            Map<String, dynamic>,
            Map<String, dynamic>,
            Map<String, dynamic>
          >);

  @override
  _i2.PostgrestTransformBuilder<dynamic> maxAffected(int? value) =>
      (super.noSuchMethod(
            Invocation.method(#maxAffected, [value]),
            returnValue: _FakePostgrestTransformBuilder_19<dynamic>(
              this,
              Invocation.method(#maxAffected, [value]),
            ),
          )
          as _i2.PostgrestTransformBuilder<dynamic>);

  @override
  _i2.PostgrestBuilder<String, String, String> explain({
    bool? analyze = false,
    bool? verbose = false,
    bool? settings = false,
    bool? buffers = false,
    bool? wal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#explain, [], {
              #analyze: analyze,
              #verbose: verbose,
              #settings: settings,
              #buffers: buffers,
              #wal: wal,
            }),
            returnValue: _FakePostgrestBuilder_16<String, String, String>(
              this,
              Invocation.method(#explain, [], {
                #analyze: analyze,
                #verbose: verbose,
                #settings: settings,
                #buffers: buffers,
                #wal: wal,
              }),
            ),
          )
          as _i2.PostgrestBuilder<String, String, String>);

  @override
  _i2.PostgrestBuilder<U, U, dynamic> withConverter<U>(
    _i2.PostgrestConverter<U, dynamic>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_16<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i2.PostgrestBuilder<U, U, dynamic>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_17(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_17(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i6.Stream<dynamic> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i6.Stream<dynamic>.empty(),
          )
          as _i6.Stream<dynamic>);

  @override
  _i6.Future<dynamic> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<U> then<U>(
    _i6.FutureOr<U> Function(dynamic)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i6.Future<U>.value(v),
                ) ??
                _FakeFuture_18<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i6.Future<U>);

  @override
  _i6.Future<dynamic> timeout(
    Duration? timeLimit, {
    _i6.FutureOr<dynamic> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> whenComplete(_i6.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}
