// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/features/auth/presentation/bloc/auth_bloc_network_failures_property_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:grex/core/utils/result.dart' as _i7;
import 'package:grex/features/auth/data/handlers/auth_deep_link_handler.dart'
    as _i13;
import 'package:grex/features/auth/domain/entities/entities.dart' as _i6;
import 'package:grex/features/auth/domain/entities/profile_setup_data.dart'
    as _i11;
import 'package:grex/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:grex/features/auth/domain/repositories/social_auth_repository.dart'
    as _i10;
import 'package:grex/features/auth/domain/repositories/user_repository.dart'
    as _i9;
import 'package:grex/features/auth/domain/services/session_manager.dart' as _i3;
import 'package:grex/features/auth/domain/services/session_service.dart'
    as _i12;
import 'package:grex/features/auth/domain/services/social_login_analytics.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionExpiryInfo_1 extends _i1.SmartFake
    implements _i3.SessionExpiryInfo {
  _FakeSessionExpiryInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i6.User?>.empty(),
          )
          as _i5.Stream<_i6.User?>);

  @override
  bool get isEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailVerified),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i6.User>(
                    this,
                    Invocation.method(#signInWithEmail, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>> signUpWithEmail({
    required String? email,
    required String? password,
    String? displayName,
    String? preferredCurrency,
    String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
              #preferredCurrency: preferredCurrency,
              #languageCode: languageCode,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i6.User>(
                    this,
                    Invocation.method(#signUpWithEmail, [], {
                      #email: email,
                      #password: password,
                      #displayName: displayName,
                      #preferredCurrency: preferredCurrency,
                      #languageCode: languageCode,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> resetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#resetPassword, [], {#email: email}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> updatePassword({
    required String? newPassword,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #newPassword: newPassword,
              #token: token,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#updatePassword, [], {
                  #newPassword: newPassword,
                  #token: token,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i7.Result<_i6.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i7.Result<_i6.User?>>.value(
              _i8.dummyValue<_i7.Result<_i6.User?>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i5.Future<_i7.Result<_i6.User?>>);

  @override
  _i5.Future<_i7.Result<bool>> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i5.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#isAuthenticated, []),
              ),
            ),
          )
          as _i5.Future<_i7.Result<bool>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> sendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#sendVerificationEmail, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#sendVerificationEmail, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> verifyEmail({
    required String? token,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token, #email: email}),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#verifyEmail, [], {
                  #token: token,
                  #email: email,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i7.Result<String>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i5.Future<_i7.Result<String>>.value(
              _i8.dummyValue<_i7.Result<String>>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
          )
          as _i5.Future<_i7.Result<String>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i9.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>> getUserProfile(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#getUserProfile, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>> createUserProfile(
    _i6.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [profile]),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#createUserProfile, [profile]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>> updateUserProfile(
    _i6.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#updateUserProfile, [profile]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile?>>
  getUserProfileByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileByEmail, [email]),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile?>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile?>(
                    this,
                    Invocation.method(#getUserProfileByEmail, [email]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile?>>);

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>
  createSocialUserProfile({
    required String? userId,
    required String? email,
    required String? displayName,
    required String? preferredCurrency,
    required String? languageCode,
    required String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSocialUserProfile, [], {
              #userId: userId,
              #email: email,
              #displayName: displayName,
              #preferredCurrency: preferredCurrency,
              #languageCode: languageCode,
              #provider: provider,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#createSocialUserProfile, [], {
                      #userId: userId,
                      #email: email,
                      #displayName: displayName,
                      #preferredCurrency: preferredCurrency,
                      #languageCode: languageCode,
                      #provider: provider,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>);
}

/// A class which mocks [SocialAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialAuthRepository extends _i1.Mock
    implements _i10.SocialAuthRepository {
  MockSocialAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i6.User>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i6.User>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>);

  @override
  _i5.Future<bool> hasUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasUserProfile, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> linkSocialProvider({
    required String? userId,
    required _i6.SocialAuthProvider? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkSocialProvider, [], {
              #userId: userId,
              #provider: provider,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#linkSocialProvider, [], {
                  #userId: userId,
                  #provider: provider,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i6.UserProfile>> createUserProfile(
    String? userId,
    _i11.ProfileSetupData? profileData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [userId, profileData]),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#createUserProfile, [
                      userId,
                      profileData,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i6.UserProfile>>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i3.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i12.SessionData?>> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.AuthFailure, _i12.SessionData?>
                >.value(
                  _FakeEither_0<_i6.AuthFailure, _i12.SessionData?>(
                    this,
                    Invocation.method(#initialize, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i12.SessionData?>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> startSession({
    required String? accessToken,
    required String? refreshToken,
    required _i6.User? user,
    required _i6.UserProfile? userProfile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startSession, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #user: user,
              #userProfile: userProfile,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#startSession, [], {
                  #accessToken: accessToken,
                  #refreshToken: refreshToken,
                  #user: user,
                  #userProfile: userProfile,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> endSession() =>
      (super.noSuchMethod(
            Invocation.method(#endSession, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#endSession, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i12.SessionData?>>
  getCurrentSession() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSession, []),
            returnValue:
                _i5.Future<
                  _i2.Either<_i6.AuthFailure, _i12.SessionData?>
                >.value(
                  _FakeEither_0<_i6.AuthFailure, _i12.SessionData?>(
                    this,
                    Invocation.method(#getCurrentSession, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i12.SessionData?>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, bool>> isSessionValid() =>
      (super.noSuchMethod(
            Invocation.method(#isSessionValid, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, bool>>.value(
              _FakeEither_0<_i6.AuthFailure, bool>(
                this,
                Invocation.method(#isSessionValid, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i12.SessionData>> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i12.SessionData>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i12.SessionData>(
                    this,
                    Invocation.method(#refreshSession, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i12.SessionData>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.SessionExpiryInfo> getExpiryInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getExpiryInfo, []),
            returnValue: _i5.Future<_i3.SessionExpiryInfo>.value(
              _FakeSessionExpiryInfo_1(
                this,
                Invocation.method(#getExpiryInfo, []),
              ),
            ),
          )
          as _i5.Future<_i3.SessionExpiryInfo>);
}

/// A class which mocks [AuthDeepLinkHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDeepLinkHandler extends _i1.Mock
    implements _i13.AuthDeepLinkHandler {
  MockAuthDeepLinkHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void Function(Uri) get onDeepLink =>
      (super.noSuchMethod(
            Invocation.getter(#onDeepLink),
            returnValue: (Uri __p0) {},
          )
          as void Function(Uri));

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> handleDeepLink(Uri? uri) =>
      (super.noSuchMethod(
            Invocation.method(#handleDeepLink, [uri]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SocialLoginAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialLoginAnalytics extends _i1.Mock
    implements _i14.SocialLoginAnalytics {
  MockSocialLoginAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void logSocialLoginInitiated(_i6.SocialAuthProvider? provider) =>
      super.noSuchMethod(
        Invocation.method(#logSocialLoginInitiated, [provider]),
        returnValueForMissingStub: null,
      );

  @override
  void logSocialLoginSuccess({
    required _i6.SocialAuthProvider? provider,
    required String? userType,
  }) => super.noSuchMethod(
    Invocation.method(#logSocialLoginSuccess, [], {
      #provider: provider,
      #userType: userType,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void logSocialLoginFailure({
    required _i6.SocialAuthProvider? provider,
    required String? errorType,
  }) => super.noSuchMethod(
    Invocation.method(#logSocialLoginFailure, [], {
      #provider: provider,
      #errorType: errorType,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void logSocialLoginCancelled(_i6.SocialAuthProvider? provider) =>
      super.noSuchMethod(
        Invocation.method(#logSocialLoginCancelled, [provider]),
        returnValueForMissingStub: null,
      );

  @override
  void logProfileSetupCompleted({
    required _i6.SocialAuthProvider? provider,
    required String? displayName,
    required String? currency,
    required String? language,
  }) => super.noSuchMethod(
    Invocation.method(#logProfileSetupCompleted, [], {
      #provider: provider,
      #displayName: displayName,
      #currency: currency,
      #language: language,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void logAccountLinking({
    required _i6.SocialAuthProvider? provider,
    required String? action,
    required String? existingEmail,
  }) => super.noSuchMethod(
    Invocation.method(#logAccountLinking, [], {
      #provider: provider,
      #action: action,
      #existingEmail: existingEmail,
    }),
    returnValueForMissingStub: null,
  );
}
