// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/features/auth/presentation/bloc/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:grex/core/utils/result.dart' as _i7;
import 'package:grex/features/auth/domain/entities/entities.dart' as _i5;
import 'package:grex/features/auth/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:grex/features/auth/domain/repositories/user_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>> getUserProfile(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>.value(
                  _FakeEither_0<_i5.UserFailure, _i5.UserProfile>(
                    this,
                    Invocation.method(#getUserProfile, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>> createUserProfile(
    _i5.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [profile]),
            returnValue:
                _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>.value(
                  _FakeEither_0<_i5.UserFailure, _i5.UserProfile>(
                    this,
                    Invocation.method(#createUserProfile, [profile]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>> updateUserProfile(
    _i5.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue:
                _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>.value(
                  _FakeEither_0<_i5.UserFailure, _i5.UserProfile>(
                    this,
                    Invocation.method(#updateUserProfile, [profile]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile?>>
  getUserProfileByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileByEmail, [email]),
            returnValue:
                _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile?>>.value(
                  _FakeEither_0<_i5.UserFailure, _i5.UserProfile?>(
                    this,
                    Invocation.method(#getUserProfileByEmail, [email]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile?>>);

  @override
  _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>
  createSocialUserProfile({
    required String? userId,
    required String? email,
    required String? displayName,
    required String? preferredCurrency,
    required String? languageCode,
    required String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSocialUserProfile, [], {
              #userId: userId,
              #email: email,
              #displayName: displayName,
              #preferredCurrency: preferredCurrency,
              #languageCode: languageCode,
              #provider: provider,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>.value(
                  _FakeEither_0<_i5.UserFailure, _i5.UserProfile>(
                    this,
                    Invocation.method(#createSocialUserProfile, [], {
                      #userId: userId,
                      #email: email,
                      #displayName: displayName,
                      #preferredCurrency: preferredCurrency,
                      #languageCode: languageCode,
                      #provider: provider,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.UserFailure, _i5.UserProfile>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  bool get isEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailVerified),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i5.User>> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.AuthFailure, _i5.User>>.value(
                  _FakeEither_0<_i5.AuthFailure, _i5.User>(
                    this,
                    Invocation.method(#signInWithEmail, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.AuthFailure, _i5.User>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i5.User>> signUpWithEmail({
    required String? email,
    required String? password,
    String? displayName,
    String? preferredCurrency,
    String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
              #preferredCurrency: preferredCurrency,
              #languageCode: languageCode,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.AuthFailure, _i5.User>>.value(
                  _FakeEither_0<_i5.AuthFailure, _i5.User>(
                    this,
                    Invocation.method(#signUpWithEmail, [], {
                      #email: email,
                      #password: password,
                      #displayName: displayName,
                      #preferredCurrency: preferredCurrency,
                      #languageCode: languageCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.AuthFailure, _i5.User>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, void>>.value(
              _FakeEither_0<_i5.AuthFailure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.AuthFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, void>> resetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, void>>.value(
              _FakeEither_0<_i5.AuthFailure, void>(
                this,
                Invocation.method(#resetPassword, [], {#email: email}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.AuthFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, void>> updatePassword({
    required String? newPassword,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #newPassword: newPassword,
              #token: token,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, void>>.value(
              _FakeEither_0<_i5.AuthFailure, void>(
                this,
                Invocation.method(#updatePassword, [], {
                  #newPassword: newPassword,
                  #token: token,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.AuthFailure, void>>);

  @override
  _i4.Future<_i7.Result<_i5.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i7.Result<_i5.User?>>.value(
              _i8.dummyValue<_i7.Result<_i5.User?>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i7.Result<_i5.User?>>);

  @override
  _i4.Future<_i7.Result<bool>> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i4.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#isAuthenticated, []),
              ),
            ),
          )
          as _i4.Future<_i7.Result<bool>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, void>> sendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#sendVerificationEmail, []),
            returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, void>>.value(
              _FakeEither_0<_i5.AuthFailure, void>(
                this,
                Invocation.method(#sendVerificationEmail, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.AuthFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, void>> verifyEmail({
    required String? token,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token, #email: email}),
            returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, void>>.value(
              _FakeEither_0<_i5.AuthFailure, void>(
                this,
                Invocation.method(#verifyEmail, [], {
                  #token: token,
                  #email: email,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.AuthFailure, void>>);

  @override
  _i4.Future<_i7.Result<String>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<_i7.Result<String>>.value(
              _i8.dummyValue<_i7.Result<String>>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
          )
          as _i4.Future<_i7.Result<String>>);
}
