// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/features/auth/data/repositories/supabase_social_auth_repository_nonce_property_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:grex/features/auth/domain/services/nonce_generator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNonceResult_0 extends _i1.SmartFake implements _i2.NonceResult {
  _FakeNonceResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NonceGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockNonceGenerator extends _i1.Mock implements _i2.NonceGenerator {
  MockNonceGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.NonceResult> generateNonce({int? length = 32}) =>
      (super.noSuchMethod(
            Invocation.method(#generateNonce, [], {#length: length}),
            returnValue: _i3.Future<_i2.NonceResult>.value(
              _FakeNonceResult_0(
                this,
                Invocation.method(#generateNonce, [], {#length: length}),
              ),
            ),
          )
          as _i3.Future<_i2.NonceResult>);

  @override
  bool validateNonce(String? nonce) =>
      (super.noSuchMethod(
            Invocation.method(#validateNonce, [nonce]),
            returnValue: false,
          )
          as bool);

  @override
  void clearUsedNonces() => super.noSuchMethod(
    Invocation.method(#clearUsedNonces, []),
    returnValueForMissingStub: null,
  );
}
