// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/features/groups/presentation/bloc/group_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:grex/features/groups/domain/entities/group.dart' as _i6;
import 'package:grex/features/groups/domain/entities/group_member.dart' as _i7;
import 'package:grex/features/groups/domain/entities/member_role.dart' as _i8;
import 'package:grex/features/groups/domain/failures/group_failure.dart' as _i5;
import 'package:grex/features/groups/domain/repositories/group_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i3.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, List<_i6.Group>>> getUserGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getUserGroups, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.GroupFailure, List<_i6.Group>>>.value(
                  _FakeEither_0<_i5.GroupFailure, List<_i6.Group>>(
                    this,
                    Invocation.method(#getUserGroups, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, List<_i6.Group>>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>> createGroup({
    required String? name,
    required String? currency,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [], {
              #name: name,
              #currency: currency,
              #description: description,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>>.value(
                  _FakeEither_0<_i5.GroupFailure, _i6.Group>(
                    this,
                    Invocation.method(#createGroup, [], {
                      #name: name,
                      #currency: currency,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>> updateGroup({
    required String? groupId,
    String? name,
    String? currency,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroup, [], {
              #groupId: groupId,
              #name: name,
              #currency: currency,
              #description: description,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>>.value(
                  _FakeEither_0<_i5.GroupFailure, _i6.Group>(
                    this,
                    Invocation.method(#updateGroup, [], {
                      #groupId: groupId,
                      #name: name,
                      #currency: currency,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, _i7.GroupMember>> inviteMember({
    required String? groupId,
    required String? email,
    required String? displayName,
    _i8.MemberRole? role = _i8.MemberRole.editor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#inviteMember, [], {
              #groupId: groupId,
              #email: email,
              #displayName: displayName,
              #role: role,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.GroupFailure, _i7.GroupMember>>.value(
                  _FakeEither_0<_i5.GroupFailure, _i7.GroupMember>(
                    this,
                    Invocation.method(#inviteMember, [], {
                      #groupId: groupId,
                      #email: email,
                      #displayName: displayName,
                      #role: role,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, _i7.GroupMember>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, _i7.GroupMember>> updateMemberRole({
    required String? groupId,
    required String? userId,
    required _i8.MemberRole? newRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemberRole, [], {
              #groupId: groupId,
              #userId: userId,
              #newRole: newRole,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.GroupFailure, _i7.GroupMember>>.value(
                  _FakeEither_0<_i5.GroupFailure, _i7.GroupMember>(
                    this,
                    Invocation.method(#updateMemberRole, [], {
                      #groupId: groupId,
                      #userId: userId,
                      #newRole: newRole,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, _i7.GroupMember>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, void>> removeMember({
    required String? groupId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [], {
              #groupId: groupId,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.GroupFailure, void>>.value(
              _FakeEither_0<_i5.GroupFailure, void>(
                this,
                Invocation.method(#removeMember, [], {
                  #groupId: groupId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>> getGroupById(
    String? groupId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupById, [groupId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>>.value(
                  _FakeEither_0<_i5.GroupFailure, _i6.Group>(
                    this,
                    Invocation.method(#getGroupById, [groupId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, _i6.Group>>);

  @override
  _i4.Stream<List<_i6.Group>> watchUserGroups() =>
      (super.noSuchMethod(
            Invocation.method(#watchUserGroups, []),
            returnValue: _i4.Stream<List<_i6.Group>>.empty(),
          )
          as _i4.Stream<List<_i6.Group>>);

  @override
  _i4.Stream<_i6.Group> watchGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#watchGroup, [groupId]),
            returnValue: _i4.Stream<_i6.Group>.empty(),
          )
          as _i4.Stream<_i6.Group>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, bool>> hasPermission(
    String? groupId,
    String? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [groupId, action]),
            returnValue: _i4.Future<_i2.Either<_i5.GroupFailure, bool>>.value(
              _FakeEither_0<_i5.GroupFailure, bool>(
                this,
                Invocation.method(#hasPermission, [groupId, action]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, void>> leaveGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveGroup, [groupId]),
            returnValue: _i4.Future<_i2.Either<_i5.GroupFailure, void>>.value(
              _FakeEither_0<_i5.GroupFailure, void>(
                this,
                Invocation.method(#leaveGroup, [groupId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.GroupFailure, void>> deleteGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGroup, [groupId]),
            returnValue: _i4.Future<_i2.Either<_i5.GroupFailure, void>>.value(
              _FakeEither_0<_i5.GroupFailure, void>(
                this,
                Invocation.method(#deleteGroup, [groupId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.GroupFailure, void>>);
}
