// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/features/payments/presentation/bloc/payment_bloc_property_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:grex/features/payments/domain/entities/payment.dart' as _i6;
import 'package:grex/features/payments/domain/failures/payment_failure.dart'
    as _i5;
import 'package:grex/features/payments/domain/repositories/payment_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i3.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>
  getGroupPayments(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupPayments, [groupId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PaymentFailure, List<_i6.Payment>>
                >.value(
                  _FakeEither_0<_i5.PaymentFailure, List<_i6.Payment>>(
                    this,
                    Invocation.method(#getGroupPayments, [groupId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, _i6.Payment>> createPayment(
    _i6.Payment? payment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPayment, [payment]),
            returnValue:
                _i4.Future<_i2.Either<_i5.PaymentFailure, _i6.Payment>>.value(
                  _FakeEither_0<_i5.PaymentFailure, _i6.Payment>(
                    this,
                    Invocation.method(#createPayment, [payment]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, _i6.Payment>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, void>> deletePayment(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayment, [paymentId]),
            returnValue: _i4.Future<_i2.Either<_i5.PaymentFailure, void>>.value(
              _FakeEither_0<_i5.PaymentFailure, void>(
                this,
                Invocation.method(#deletePayment, [paymentId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, _i6.Payment>> getPaymentById(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentById, [paymentId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.PaymentFailure, _i6.Payment>>.value(
                  _FakeEither_0<_i5.PaymentFailure, _i6.Payment>(
                    this,
                    Invocation.method(#getPaymentById, [paymentId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, _i6.Payment>>);

  @override
  _i4.Stream<List<_i6.Payment>> watchGroupPayments(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#watchGroupPayments, [groupId]),
            returnValue: _i4.Stream<List<_i6.Payment>>.empty(),
          )
          as _i4.Stream<List<_i6.Payment>>);

  @override
  _i4.Stream<_i6.Payment> watchPayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPayment, [paymentId]),
            returnValue: _i4.Stream<_i6.Payment>.empty(),
          )
          as _i4.Stream<_i6.Payment>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>
  getPaymentsPaginated(String? groupId, {int? limit = 20, int? offset = 0}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaymentsPaginated,
              [groupId],
              {#limit: limit, #offset: offset},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PaymentFailure, List<_i6.Payment>>
                >.value(
                  _FakeEither_0<_i5.PaymentFailure, List<_i6.Payment>>(
                    this,
                    Invocation.method(
                      #getPaymentsPaginated,
                      [groupId],
                      {#limit: limit, #offset: offset},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>
  getPaymentsByPayer(String? groupId, String? payerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByPayer, [groupId, payerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PaymentFailure, List<_i6.Payment>>
                >.value(
                  _FakeEither_0<_i5.PaymentFailure, List<_i6.Payment>>(
                    this,
                    Invocation.method(#getPaymentsByPayer, [groupId, payerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>
  getPaymentsByRecipient(String? groupId, String? recipientId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByRecipient, [groupId, recipientId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PaymentFailure, List<_i6.Payment>>
                >.value(
                  _FakeEither_0<_i5.PaymentFailure, List<_i6.Payment>>(
                    this,
                    Invocation.method(#getPaymentsByRecipient, [
                      groupId,
                      recipientId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>
  getPaymentsBetweenUsers(String? groupId, String? userId1, String? userId2) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsBetweenUsers, [
              groupId,
              userId1,
              userId2,
            ]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.PaymentFailure, List<_i6.Payment>>
                >.value(
                  _FakeEither_0<_i5.PaymentFailure, List<_i6.Payment>>(
                    this,
                    Invocation.method(#getPaymentsBetweenUsers, [
                      groupId,
                      userId1,
                      userId2,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, List<_i6.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, bool>> hasPermission(
    String? paymentId,
    String? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, [paymentId, action]),
            returnValue: _i4.Future<_i2.Either<_i5.PaymentFailure, bool>>.value(
              _FakeEither_0<_i5.PaymentFailure, bool>(
                this,
                Invocation.method(#hasPermission, [paymentId, action]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.PaymentFailure, bool>> validatePayment(
    _i6.Payment? payment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePayment, [payment]),
            returnValue: _i4.Future<_i2.Either<_i5.PaymentFailure, bool>>.value(
              _FakeEither_0<_i5.PaymentFailure, bool>(
                this,
                Invocation.method(#validatePayment, [payment]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.PaymentFailure, bool>>);
}
