// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/features/export/presentation/pages/export_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i15;
import 'package:grex/core/services/export_service.dart' as _i2;
import 'package:grex/features/balances/domain/entities/balance.dart' as _i11;
import 'package:grex/features/balances/presentation/bloc/balance_bloc.dart'
    as _i20;
import 'package:grex/features/balances/presentation/bloc/balance_event.dart'
    as _i21;
import 'package:grex/features/balances/presentation/bloc/balance_state.dart'
    as _i6;
import 'package:grex/features/expenses/domain/entities/expense.dart' as _i9;
import 'package:grex/features/expenses/presentation/bloc/expense_bloc.dart'
    as _i16;
import 'package:grex/features/expenses/presentation/bloc/expense_event.dart'
    as _i17;
import 'package:grex/features/expenses/presentation/bloc/expense_state.dart'
    as _i4;
import 'package:grex/features/groups/domain/entities/group.dart' as _i8;
import 'package:grex/features/groups/domain/entities/member_role.dart' as _i13;
import 'package:grex/features/groups/presentation/bloc/group_bloc.dart' as _i12;
import 'package:grex/features/groups/presentation/bloc/group_event.dart'
    as _i14;
import 'package:grex/features/groups/presentation/bloc/group_state.dart' as _i3;
import 'package:grex/features/payments/domain/entities/payment.dart' as _i10;
import 'package:grex/features/payments/presentation/bloc/payment_bloc.dart'
    as _i18;
import 'package:grex/features/payments/presentation/bloc/payment_event.dart'
    as _i19;
import 'package:grex/features/payments/presentation/bloc/payment_state.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExportResult_0 extends _i1.SmartFake implements _i2.ExportResult {
  _FakeExportResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGroupState_1 extends _i1.SmartFake implements _i3.GroupState {
  _FakeGroupState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpenseState_2 extends _i1.SmartFake implements _i4.ExpenseState {
  _FakeExpenseState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentState_3 extends _i1.SmartFake implements _i5.PaymentState {
  _FakePaymentState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBalanceState_4 extends _i1.SmartFake implements _i6.BalanceState {
  _FakeBalanceState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportService extends _i1.Mock implements _i2.ExportService {
  MockExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.ExportResult> exportToCSV({
    required _i8.Group? group,
    required List<_i9.Expense>? expenses,
    required List<_i10.Payment>? payments,
    required List<_i11.Balance>? balances,
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportToCSV, [], {
              #group: group,
              #expenses: expenses,
              #payments: payments,
              #balances: balances,
              #onProgress: onProgress,
            }),
            returnValue: _i7.Future<_i2.ExportResult>.value(
              _FakeExportResult_0(
                this,
                Invocation.method(#exportToCSV, [], {
                  #group: group,
                  #expenses: expenses,
                  #payments: payments,
                  #balances: balances,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.ExportResult>);

  @override
  _i7.Future<_i2.ExportResult> exportToPDF({
    required _i8.Group? group,
    required List<_i9.Expense>? expenses,
    required List<_i10.Payment>? payments,
    required List<_i11.Balance>? balances,
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportToPDF, [], {
              #group: group,
              #expenses: expenses,
              #payments: payments,
              #balances: balances,
              #onProgress: onProgress,
            }),
            returnValue: _i7.Future<_i2.ExportResult>.value(
              _FakeExportResult_0(
                this,
                Invocation.method(#exportToPDF, [], {
                  #group: group,
                  #expenses: expenses,
                  #payments: payments,
                  #balances: balances,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.ExportResult>);

  @override
  _i7.Future<void> shareFile(String? filePath, String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#shareFile, [filePath, fileName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteExportFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExportFile, [filePath]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [GroupBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupBloc extends _i1.Mock implements _i12.GroupBloc {
  MockGroupBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GroupState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGroupState_1(this, Invocation.getter(#state)),
          )
          as _i3.GroupState);

  @override
  _i7.Stream<_i3.GroupState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i3.GroupState>.empty(),
          )
          as _i7.Stream<_i3.GroupState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool canAdministrateGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#canAdministrateGroup, [groupId]),
            returnValue: false,
          )
          as bool);

  @override
  bool canEditGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#canEditGroup, [groupId]),
            returnValue: false,
          )
          as bool);

  @override
  _i13.MemberRole? getUserRoleInGroup(String? groupId) =>
      (super.noSuchMethod(Invocation.method(#getUserRoleInGroup, [groupId]))
          as _i13.MemberRole?);

  @override
  void add(_i14.GroupEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i14.GroupEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.GroupState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i14.GroupEvent>(
    _i15.EventHandler<E, _i3.GroupState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i14.GroupEvent, _i3.GroupState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i15.Change<_i3.GroupState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ExpenseBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseBloc extends _i1.Mock implements _i16.ExpenseBloc {
  MockExpenseBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ExpenseState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeExpenseState_2(this, Invocation.getter(#state)),
          )
          as _i4.ExpenseState);

  @override
  _i7.Stream<_i4.ExpenseState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i4.ExpenseState>.empty(),
          )
          as _i7.Stream<_i4.ExpenseState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool canEditExpense(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#canEditExpense, [expenseId]),
            returnValue: false,
          )
          as bool);

  @override
  bool canDeleteExpense(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#canDeleteExpense, [expenseId]),
            returnValue: false,
          )
          as bool);

  @override
  void add(_i17.ExpenseEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i17.ExpenseEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.ExpenseState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i17.ExpenseEvent>(
    _i15.EventHandler<E, _i4.ExpenseState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i17.ExpenseEvent, _i4.ExpenseState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i15.Change<_i4.ExpenseState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PaymentBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentBloc extends _i1.Mock implements _i18.PaymentBloc {
  MockPaymentBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PaymentState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePaymentState_3(this, Invocation.getter(#state)),
          )
          as _i5.PaymentState);

  @override
  _i7.Stream<_i5.PaymentState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.PaymentState>.empty(),
          )
          as _i7.Stream<_i5.PaymentState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool canDeletePayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#canDeletePayment, [paymentId]),
            returnValue: false,
          )
          as bool);

  @override
  List<_i10.Payment> getPaymentsByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByUser, [userId]),
            returnValue: <_i10.Payment>[],
          )
          as List<_i10.Payment>);

  @override
  double getTotalPaidByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPaidByUser, [userId]),
            returnValue: 0.0,
          )
          as double);

  @override
  double getTotalReceivedByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalReceivedByUser, [userId]),
            returnValue: 0.0,
          )
          as double);

  @override
  double getNetPaymentForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNetPaymentForUser, [userId]),
            returnValue: 0.0,
          )
          as double);

  @override
  void add(_i19.PaymentEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i19.PaymentEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.PaymentState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i19.PaymentEvent>(
    _i15.EventHandler<E, _i5.PaymentState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i19.PaymentEvent, _i5.PaymentState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i15.Change<_i5.PaymentState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BalanceBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBalanceBloc extends _i1.Mock implements _i20.BalanceBloc {
  MockBalanceBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BalanceState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBalanceState_4(this, Invocation.getter(#state)),
          )
          as _i6.BalanceState);

  @override
  _i7.Stream<_i6.BalanceState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i6.BalanceState>.empty(),
          )
          as _i7.Stream<_i6.BalanceState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void add(_i21.BalanceEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i21.BalanceEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.BalanceState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i21.BalanceEvent>(
    _i15.EventHandler<E, _i6.BalanceState>? handler, {
    _i15.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i15.Transition<_i21.BalanceEvent, _i6.BalanceState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i15.Change<_i6.BalanceState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
