// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/helpers/mock_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/foundation.dart' as _i10;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i5;
import 'package:grex/core/performance/performance_service.dart' as _i8;
import 'package:grex/features/auth/domain/entities/entities.dart' as _i7;
import 'package:grex/features/auth/domain/repositories/user_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:supabase/supabase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_2 extends _i1.SmartFake
    implements _i4.FunctionsClient {
  _FakeFunctionsClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_3 extends _i1.SmartFake
    implements _i4.SupabaseStorageClient {
  _FakeSupabaseStorageClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_4 extends _i1.SmartFake
    implements _i4.RealtimeClient {
  _FakeRealtimeClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_5 extends _i1.SmartFake
    implements _i4.PostgrestClient {
  _FakePostgrestClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_6 extends _i1.SmartFake implements _i4.GoTrueClient {
  _FakeGoTrueClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_7 extends _i1.SmartFake
    implements _i4.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_8 extends _i1.SmartFake
    implements _i4.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_9<T1> extends _i1.SmartFake
    implements _i4.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_10 extends _i1.SmartFake
    implements _i4.RealtimeChannel {
  _FakeRealtimeChannel_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueAdminApi_11 extends _i1.SmartFake
    implements _i4.GoTrueAdminApi {
  _FakeGoTrueAdminApi_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueMFAApi_12 extends _i1.SmartFake implements _i4.GoTrueMFAApi {
  _FakeGoTrueMFAApi_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_13 extends _i1.SmartFake implements _i4.AuthResponse {
  _FakeAuthResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthResponse_14 extends _i1.SmartFake implements _i4.OAuthResponse {
  _FakeOAuthResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionUrlResponse_15 extends _i1.SmartFake
    implements _i4.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResendResponse_16 extends _i1.SmartFake
    implements _i4.ResendResponse {
  _FakeResendResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_17 extends _i1.SmartFake implements _i4.UserResponse {
  _FakeUserResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObject_18 extends _i1.SmartFake implements Object {
  _FakeObject_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetClaimsResponse_19 extends _i1.SmartFake
    implements _i4.GetClaimsResponse {
  _FakeGetClaimsResponse_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_20 extends _i1.SmartFake implements _i5.IOSOptions {
  _FakeIOSOptions_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_21 extends _i1.SmartFake
    implements _i5.AndroidOptions {
  _FakeAndroidOptions_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_22 extends _i1.SmartFake implements _i5.LinuxOptions {
  _FakeLinuxOptions_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_23 extends _i1.SmartFake
    implements _i5.WindowsOptions {
  _FakeWindowsOptions_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_24 extends _i1.SmartFake implements _i5.WebOptions {
  _FakeWebOptions_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_25 extends _i1.SmartFake implements _i5.MacOsOptions {
  _FakeMacOsOptions_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_26 extends _i1.SmartFake implements _i4.User {
  _FakeUser_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_27 extends _i1.SmartFake implements _i4.Session {
  _FakeSession_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>> getUserProfile(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue:
                _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>.value(
                  _FakeEither_0<_i7.UserFailure, _i7.UserProfile>(
                    this,
                    Invocation.method(#getUserProfile, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>);

  @override
  _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>> createUserProfile(
    _i7.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [profile]),
            returnValue:
                _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>.value(
                  _FakeEither_0<_i7.UserFailure, _i7.UserProfile>(
                    this,
                    Invocation.method(#createUserProfile, [profile]),
                  ),
                ),
          )
          as _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>);

  @override
  _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>> updateUserProfile(
    _i7.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue:
                _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>.value(
                  _FakeEither_0<_i7.UserFailure, _i7.UserProfile>(
                    this,
                    Invocation.method(#updateUserProfile, [profile]),
                  ),
                ),
          )
          as _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>);

  @override
  _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile?>>
  getUserProfileByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileByEmail, [email]),
            returnValue:
                _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile?>>.value(
                  _FakeEither_0<_i7.UserFailure, _i7.UserProfile?>(
                    this,
                    Invocation.method(#getUserProfileByEmail, [email]),
                  ),
                ),
          )
          as _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile?>>);

  @override
  _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>
  createSocialUserProfile({
    required String? userId,
    required String? email,
    required String? displayName,
    required String? preferredCurrency,
    required String? languageCode,
    required String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSocialUserProfile, [], {
              #userId: userId,
              #email: email,
              #displayName: displayName,
              #preferredCurrency: preferredCurrency,
              #languageCode: languageCode,
              #provider: provider,
            }),
            returnValue:
                _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>.value(
                  _FakeEither_0<_i7.UserFailure, _i7.UserProfile>(
                    this,
                    Invocation.method(#createSocialUserProfile, [], {
                      #userId: userId,
                      #email: email,
                      #displayName: displayName,
                      #preferredCurrency: preferredCurrency,
                      #languageCode: languageCode,
                      #provider: provider,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.Either<_i7.UserFailure, _i7.UserProfile>>);
}

/// A class which mocks [PerformanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerformanceService extends _i1.Mock
    implements _i8.PerformanceService {
  MockPerformanceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  _i8.PerformanceTrace? startTrace(String? name) =>
      (super.noSuchMethod(Invocation.method(#startTrace, [name]))
          as _i8.PerformanceTrace?);

  @override
  _i3.Future<T> measureOperation<T>({
    required String? name,
    required _i3.Future<T> Function()? operation,
    Map<String, String>? attributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#measureOperation, [], {
              #name: name,
              #operation: operation,
              #attributes: attributes,
            }),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#measureOperation, [], {
                      #name: name,
                      #operation: operation,
                      #attributes: attributes,
                    }),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#measureOperation, [], {
                    #name: name,
                    #operation: operation,
                    #attributes: attributes,
                  }),
                ),
          )
          as _i3.Future<T>);

  @override
  T measureSyncOperation<T>({
    required String? name,
    required T Function()? operation,
    Map<String, String>? attributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#measureSyncOperation, [], {
              #name: name,
              #operation: operation,
              #attributes: attributes,
            }),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#measureSyncOperation, [], {
                #name: name,
                #operation: operation,
                #attributes: attributes,
              }),
            ),
          )
          as T);

  @override
  T measureSyncComputation<T>({
    required String? operationName,
    required T Function()? computation,
    Map<String, String>? attributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#measureSyncComputation, [], {
              #operationName: operationName,
              #computation: computation,
              #attributes: attributes,
            }),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#measureSyncComputation, [], {
                #operationName: operationName,
                #computation: computation,
                #attributes: attributes,
              }),
            ),
          )
          as T);

  @override
  _i8.PerformanceTrace? startHttpTrace(String? method, String? path) =>
      (super.noSuchMethod(Invocation.method(#startHttpTrace, [method, path]))
          as _i8.PerformanceTrace?);

  @override
  _i8.PerformanceTrace? startScreenTrace(String? screenName) =>
      (super.noSuchMethod(Invocation.method(#startScreenTrace, [screenName]))
          as _i8.PerformanceTrace?);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i4.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_2(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i4.FunctionsClient);

  @override
  _i4.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_3(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.SupabaseStorageClient);

  @override
  _i4.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_4(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i4.RealtimeClient);

  @override
  _i4.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_5(this, Invocation.getter(#rest)),
          )
          as _i4.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i4.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_6(this, Invocation.getter(#auth)),
          )
          as _i4.GoTrueClient);

  @override
  set functions(_i4.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i4.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i4.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i4.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i4.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_7(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i4.SupabaseQueryBuilder);

  @override
  _i4.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_8(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i4.SupabaseQuerySchema);

  @override
  _i4.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_9<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i4.PostgrestFilterBuilder<T>);

  @override
  _i4.RealtimeChannel channel(
    String? name, {
    _i4.RealtimeChannelConfig? opts = const _i4.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_10(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i4.RealtimeChannel);

  @override
  List<_i4.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i4.RealtimeChannel>[],
          )
          as List<_i4.RealtimeChannel>);

  @override
  _i3.Future<String> removeChannel(_i4.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i3.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i4.GoTrueClient {
  MockGoTrueClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GoTrueAdminApi get admin =>
      (super.noSuchMethod(
            Invocation.getter(#admin),
            returnValue: _FakeGoTrueAdminApi_11(
              this,
              Invocation.getter(#admin),
            ),
          )
          as _i4.GoTrueAdminApi);

  @override
  _i4.GoTrueMFAApi get mfa =>
      (super.noSuchMethod(
            Invocation.getter(#mfa),
            returnValue: _FakeGoTrueMFAApi_12(this, Invocation.getter(#mfa)),
          )
          as _i4.GoTrueMFAApi);

  @override
  _i3.Stream<_i4.AuthState> get onAuthStateChange =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChange),
            returnValue: _i3.Stream<_i4.AuthState>.empty(),
          )
          as _i3.Stream<_i4.AuthState>);

  @override
  _i3.Stream<_i4.AuthState> get onAuthStateChangeSync =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChangeSync),
            returnValue: _i3.Stream<_i4.AuthState>.empty(),
          )
          as _i3.Stream<_i4.AuthState>);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set admin(_i4.GoTrueAdminApi? value) => super.noSuchMethod(
    Invocation.setter(#admin, value),
    returnValueForMissingStub: null,
  );

  @override
  set mfa(_i4.GoTrueMFAApi? value) => super.noSuchMethod(
    Invocation.setter(#mfa, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i4.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, [], {
              #data: data,
              #captchaToken: captchaToken,
            }),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<_i4.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i4.OtpChannel? channel = _i4.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<_i4.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            }),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<_i4.OAuthResponse> getOAuthSignInUrl({
    required _i4.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOAuthSignInUrl, [], {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            }),
            returnValue: _i3.Future<_i4.OAuthResponse>.value(
              _FakeOAuthResponse_14(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.OAuthResponse>);

  @override
  _i3.Future<_i4.AuthSessionUrlResponse> exchangeCodeForSession(
    String? authCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [authCode]),
            returnValue: _i3.Future<_i4.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_15(
                this,
                Invocation.method(#exchangeCodeForSession, [authCode]),
              ),
            ),
          )
          as _i3.Future<_i4.AuthSessionUrlResponse>);

  @override
  _i3.Future<_i4.AuthResponse> signInWithIdToken({
    required _i4.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i4.OtpChannel? channel = _i4.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOtp, [], {
              #email: email,
              #phone: phone,
              #emailRedirectTo: emailRedirectTo,
              #shouldCreateUser: shouldCreateUser,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i4.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            }),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSSOSignInUrl, [], {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i3.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i4.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, [refreshToken]),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<void> reauthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ResendResponse> resend({
    String? email,
    String? phone,
    required _i4.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [], {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i3.Future<_i4.ResendResponse>.value(
              _FakeResendResponse_16(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ResendResponse>);

  @override
  _i3.Future<_i4.UserResponse> getUser([String? jwt]) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [jwt]),
            returnValue: _i3.Future<_i4.UserResponse>.value(
              _FakeUserResponse_17(this, Invocation.method(#getUser, [jwt])),
            ),
          )
          as _i3.Future<_i4.UserResponse>);

  @override
  _i3.Future<_i4.UserResponse> updateUser(
    _i4.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [attributes],
              {#emailRedirectTo: emailRedirectTo},
            ),
            returnValue: _i3.Future<_i4.UserResponse>.value(
              _FakeUserResponse_17(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.UserResponse>);

  @override
  _i3.Future<_i4.AuthResponse> setSession(
    String? refreshToken, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSession,
              [refreshToken],
              {#accessToken: accessToken},
            ),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(
                  #setSession,
                  [refreshToken],
                  {#accessToken: accessToken},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<_i4.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSessionFromUrl,
              [originUrl],
              {#storeSession: storeSession},
            ),
            returnValue: _i3.Future<_i4.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_15(
                this,
                Invocation.method(
                  #getSessionFromUrl,
                  [originUrl],
                  {#storeSession: storeSession},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.AuthSessionUrlResponse>);

  @override
  _i3.Future<void> signOut({
    _i4.SignOutScope? scope = _i4.SignOutScope.local,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#scope: scope}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetPasswordForEmail,
              [email],
              {#redirectTo: redirectTo, #captchaToken: captchaToken},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.UserIdentity>> getUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentities, []),
            returnValue: _i3.Future<List<_i4.UserIdentity>>.value(
              <_i4.UserIdentity>[],
            ),
          )
          as _i3.Future<List<_i4.UserIdentity>>);

  @override
  _i3.Future<_i4.AuthResponse> linkIdentityWithIdToken({
    required _i4.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkIdentityWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  _i3.Future<_i4.OAuthResponse> getLinkIdentityUrl(
    _i4.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLinkIdentityUrl,
              [provider],
              {
                #redirectTo: redirectTo,
                #scopes: scopes,
                #queryParams: queryParams,
              },
            ),
            returnValue: _i3.Future<_i4.OAuthResponse>.value(
              _FakeOAuthResponse_14(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.OAuthResponse>);

  @override
  _i3.Future<void> unlinkIdentity(_i4.UserIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkIdentity, [identity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setInitialSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialSession, [jsonStr]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSession, [jsonStr]),
            returnValue: _i3.Future<_i4.AuthResponse>.value(
              _FakeAuthResponse_13(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
          )
          as _i3.Future<_i4.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
    Invocation.method(#stopAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAllSubscribers(
    _i4.AuthChangeEvent? event, {
    _i4.Session? session,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #notifyAllSubscribers,
      [event],
      {#session: session, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Object notifyException(Object? exception, [StackTrace? stackTrace]) =>
      (super.noSuchMethod(
            Invocation.method(#notifyException, [exception, stackTrace]),
            returnValue: _FakeObject_18(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
          )
          as Object);

  @override
  _i3.Future<_i4.GetClaimsResponse> getClaims([
    String? jwt,
    _i4.GetClaimsOptions? options,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getClaims, [jwt, options]),
            returnValue: _i3.Future<_i4.GetClaimsResponse>.value(
              _FakeGetClaimsResponse_19(
                this,
                Invocation.method(#getClaims, [jwt, options]),
              ),
            ),
          )
          as _i3.Future<_i4.GetClaimsResponse>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseUser extends _i1.Mock implements _i4.User {
  MockSupabaseUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#aud)),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i5.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_20(this, Invocation.getter(#iOptions)),
          )
          as _i5.IOSOptions);

  @override
  _i5.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_21(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i5.AndroidOptions);

  @override
  _i5.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_22(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i5.LinuxOptions);

  @override
  _i5.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_23(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i5.WindowsOptions);

  @override
  _i5.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_24(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i5.WebOptions);

  @override
  _i5.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_25(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i5.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i10.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i10.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> write({
    required String? key,
    required String? value,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> read({
    required String? key,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> containsKey({
    required String? key,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> delete({
    required String? key,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> readAll({
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> deleteAll({
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i4.Session {
  MockSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
          )
          as String);

  @override
  String get tokenType =>
      (super.noSuchMethod(
            Invocation.getter(#tokenType),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
          )
          as String);

  @override
  _i4.User get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeUser_26(this, Invocation.getter(#user)),
          )
          as _i4.User);

  @override
  bool get isExpired =>
      (super.noSuchMethod(Invocation.getter(#isExpired), returnValue: false)
          as bool);

  @override
  set expiresAt(int? value) => super.noSuchMethod(
    Invocation.setter(#expiresAt, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.Session copyWith({
    String? accessToken,
    int? expiresIn,
    String? refreshToken,
    String? tokenType,
    String? providerToken,
    String? providerRefreshToken,
    _i4.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #accessToken: accessToken,
              #expiresIn: expiresIn,
              #refreshToken: refreshToken,
              #tokenType: tokenType,
              #providerToken: providerToken,
              #providerRefreshToken: providerRefreshToken,
              #user: user,
            }),
            returnValue: _FakeSession_27(
              this,
              Invocation.method(#copyWith, [], {
                #accessToken: accessToken,
                #expiresIn: expiresIn,
                #refreshToken: refreshToken,
                #tokenType: tokenType,
                #providerToken: providerToken,
                #providerRefreshToken: providerRefreshToken,
                #user: user,
              }),
            ),
          )
          as _i4.Session);
}

/// A class which mocks [AuthResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthResponse extends _i1.Mock implements _i4.AuthResponse {
  MockAuthResponse() {
    _i1.throwOnMissingStub(this);
  }
}
