// Mocks generated by Mockito 5.4.6 from annotations
// in grex/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:grex/features/auth/domain/entities/entities.dart' as _i6;
import 'package:grex/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:grex/features/auth/domain/repositories/user_repository.dart'
    as _i7;
import 'package:grex/features/auth/domain/services/email_verification_service.dart'
    as _i9;
import 'package:grex/features/auth/domain/services/session_manager.dart' as _i3;
import 'package:grex/features/auth/domain/services/session_service.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionExpiryInfo_1 extends _i1.SmartFake
    implements _i3.SessionExpiryInfo {
  _FakeSessionExpiryInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i6.User?>.empty(),
          )
          as _i5.Stream<_i6.User?>);

  @override
  bool get isEmailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isEmailVerified),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i6.User>(
                    this,
                    Invocation.method(#signInWithEmail, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>> signUpWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i6.User>(
                    this,
                    Invocation.method(#signUpWithEmail, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i6.User>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> resetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#resetPassword, [], {#email: email}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> sendVerificationEmail() =>
      (super.noSuchMethod(
            Invocation.method(#sendVerificationEmail, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#sendVerificationEmail, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> verifyEmail({
    required String? token,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token, #email: email}),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#verifyEmail, [], {
                  #token: token,
                  #email: email,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>> getUserProfile(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#getUserProfile, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>> createUserProfile(
    _i6.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [profile]),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#createUserProfile, [profile]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>);

  @override
  _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>> updateUserProfile(
    _i6.UserProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue:
                _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>.value(
                  _FakeEither_0<_i6.UserFailure, _i6.UserProfile>(
                    this,
                    Invocation.method(#updateUserProfile, [profile]),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.UserFailure, _i6.UserProfile>>);
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i8.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> storeSession({
    required String? accessToken,
    required String? refreshToken,
    required _i6.User? user,
    required _i6.UserProfile? userProfile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#storeSession, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #user: user,
              #userProfile: userProfile,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#storeSession, [], {
                  #accessToken: accessToken,
                  #refreshToken: refreshToken,
                  #user: user,
                  #userProfile: userProfile,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>
  getStoredSession() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredSession, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i8.SessionData?>(
                    this,
                    Invocation.method(#getStoredSession, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, bool>> validateSession() =>
      (super.noSuchMethod(
            Invocation.method(#validateSession, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, bool>>.value(
              _FakeEither_0<_i6.AuthFailure, bool>(
                this,
                Invocation.method(#validateSession, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData>> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i8.SessionData>(
                    this,
                    Invocation.method(#refreshSession, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#clearSession, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<bool> hasStoredSession() =>
      (super.noSuchMethod(
            Invocation.method(#hasStoredSession, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<DateTime?> getSessionExpiry() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionExpiry, []),
            returnValue: _i5.Future<DateTime?>.value(),
          )
          as _i5.Future<DateTime?>);

  @override
  _i5.Future<bool> isSessionExpired() =>
      (super.noSuchMethod(
            Invocation.method(#isSessionExpired, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [SessionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionManager extends _i1.Mock implements _i3.SessionManager {
  MockSessionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i8.SessionData?>(
                    this,
                    Invocation.method(#initialize, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> startSession({
    required String? accessToken,
    required String? refreshToken,
    required _i6.User? user,
    required _i6.UserProfile? userProfile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startSession, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #user: user,
              #userProfile: userProfile,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#startSession, [], {
                  #accessToken: accessToken,
                  #refreshToken: refreshToken,
                  #user: user,
                  #userProfile: userProfile,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, void>> endSession() =>
      (super.noSuchMethod(
            Invocation.method(#endSession, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, void>>.value(
              _FakeEither_0<_i6.AuthFailure, void>(
                this,
                Invocation.method(#endSession, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>
  getCurrentSession() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSession, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i8.SessionData?>(
                    this,
                    Invocation.method(#getCurrentSession, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData?>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, bool>> isSessionValid() =>
      (super.noSuchMethod(
            Invocation.method(#isSessionValid, []),
            returnValue: _i5.Future<_i2.Either<_i6.AuthFailure, bool>>.value(
              _FakeEither_0<_i6.AuthFailure, bool>(
                this,
                Invocation.method(#isSessionValid, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, bool>>);

  @override
  _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData>> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData>>.value(
                  _FakeEither_0<_i6.AuthFailure, _i8.SessionData>(
                    this,
                    Invocation.method(#refreshSession, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.AuthFailure, _i8.SessionData>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.SessionExpiryInfo> getExpiryInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getExpiryInfo, []),
            returnValue: _i5.Future<_i3.SessionExpiryInfo>.value(
              _FakeSessionExpiryInfo_1(
                this,
                Invocation.method(#getExpiryInfo, []),
              ),
            ),
          )
          as _i5.Future<_i3.SessionExpiryInfo>);
}

/// A class which mocks [EmailVerificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailVerificationService extends _i1.Mock
    implements _i9.EmailVerificationService {
  MockEmailVerificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Either<_i6.AuthFailure, _i9.EmailVerificationData>
  processVerificationLink(String? link) =>
      (super.noSuchMethod(
            Invocation.method(#processVerificationLink, [link]),
            returnValue:
                _FakeEither_0<_i6.AuthFailure, _i9.EmailVerificationData>(
                  this,
                  Invocation.method(#processVerificationLink, [link]),
                ),
          )
          as _i2.Either<_i6.AuthFailure, _i9.EmailVerificationData>);

  @override
  bool isVerificationLink(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#isVerificationLink, [url]),
            returnValue: false,
          )
          as bool);

  @override
  String? extractToken(String? link) =>
      (super.noSuchMethod(Invocation.method(#extractToken, [link])) as String?);

  @override
  String? extractEmail(String? link) =>
      (super.noSuchMethod(Invocation.method(#extractEmail, [link])) as String?);
}
